### PR TITLE
MINOR: DataObject->fieldLabels() will only return an array

### LINKED ISSUE #3028: DataObject->fieldLabels() php docs wrong?
The docblock of `DataObject->fieldLabels()` wants to tell us that it returns array or string:

```
* @return array|string Array of all element labels if no argument given, otherwise the label of the field
```

however, in the code I can find no indication that would support that claim. am I missing something?

https://github.com/silverstripe/silverstripe-framework/blob/90ba514cda604cbd8e97537e7d95a8188dd45d63/model/DataObject.php#L3279

### PR DESCRIPTION
**Pull request by lukereative**
Fixes #3028

### CODE REVIEW

File: src/ORM/DataObject.php [hunk 1]
```diff
@@ -3495,7 +3495,7 @@ public function searchableFields()
      *
      * @param boolean $includerelations a boolean value to indicate if the labels returned include relation fields
      *
-     * @return array|string Array of all element labels if no argument given, otherwise the label of the field
+     * @return array Array of all element labels if no argument given, otherwise the label of the field
```
Comment (robbieaverill) [inline src/ORM/DataObject.php]: The "otherwise" part is the bit that was where it said it'd return a string right? Should we remove that too?

Comment (lukereative) [reply src/ORM/DataObject.php]: Done
