### PR TITLE
BUG Fixed handling of numbers in certain locales.

### LINKED ISSUE #2161: I18n NumericField
When you use the NumericField and set your local to a country that uses a , instead of a . you get some problems.

The validator works, there is a check with Zend_Locale_Format and your local wil be used. But when you save the value a 0 is send to the database. The problem is in 
```php
public function dataValue() {
	return (is_numeric($this->value)) ? $this->value : 0;
}
```
the function expects a . instead of a ,. So the is_numeric returns false, you can use the check from Zend_Local_Format, but if your database expects a numer you need a . instead of a ,. I fixed this by making the function look like this:

```php
public function dataValue() {
	return Zend_Locale_Format::isNumber(trim($this->value), array('locale' => i18n::get_locale())) ? str_replace(',', '.', $this->value) : 0;
}
```

There still is one little problem now, when you reload your data in the field, it wil automatically use a . instead of ,. So when you save the data, you get een a validation error.

To fix this I override the setValue function to something like this:
```php
	public function setValue($value) {
		return parent::setValue(Zend_Locale_Format::toNumber($value));
	}
```

You have to do the first replace, when you load the data from the database there is a . instead of the expected ,.

I'm not working in php a lot, so maybe there is a better way to fix this. That's why I send a bug report and not a pull request.

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #2161

@lekoala, @jurriaan, @andrelohmann 

Do you like this solution?

Credit to @andrelohmann for beginning this solution.

### CODE REVIEW

**Comment by dhensby** [comment]
Ok, cool. Looks good to me, any final thoughts?

File: forms/NumericField.php [hunk 1]
```diff
@@ -9,6 +9,50 @@
...
 
+	public function setValue($value, $data = array()) {
+		require_once "Zend/Locale/Format.php";
+
+		// If passing in a non-string number, or a value
+		// directly from a dataobject then localise this number
+		if ((is_numeric($value) && !is_string($value)) || 
+			($value && $data instanceof DataObject)
+		){
+			$locale = new Zend_Locale(i18n::get_locale());
```
Comment (chillu) [inline forms/NumericField.php]: I would prefer to follow the `DateField` precedent here and use a `setLocale()` that defaults to `i18n::get_locale()`, make the field a bit more versatile.

Comment (tractorcow) [inline forms/NumericField.php]: Point taken, I'll add as suggested. :)

**Comment by tractorcow** [comment]
@chillu your feedback has been taken into consideration. NumericField now has getLocale and setLocale, which defaults to `i18n::get_locale()`

File: forms/NumericField.php [hunk 2]
```diff
@@ -2,13 +2,63 @@
...
  * @subpackage fields-formattedinput
  */
 class NumericField extends TextField {
 
+	/**
+	 * @var string
+	 */
+	protected $locale = null;
+
+	public function setValue($value, $data = array()) {
```
Comment (chillu) [inline forms/NumericField.php]: PHPDoc? ;)

File: forms/NumericField.php [hunk 3]
```diff
@@ -2,13 +2,63 @@
...
+		return $this;
+	}
+
+	/**
+	 * In some cases and locales, validation expects non-breaking spaces
+	 *
+	 * @param string $input
+	 * @return string The input value, with all spaces replaced with non-breaking spaces
+	 */
+	public static function clean($input) {
```
Comment (chillu) [inline forms/NumericField.php]: Not sure if we should make this a public API - I'd expect other fields to have similar methods then. It's also a bit unclear if you're supposed to run this specifically on input before handing it to NumericField, or if its taken care of automatically. It's also used inconsistently as static (in tests) and instance method (in IsNumeric). Can we just fold this logic into its one non-test based use case? I think its better to repeat it in tests than to increase the API surface.

File: forms/NumericField.php (hunk 2 above)
Comment (tractorcow) [inline forms/NumericField.php]: PHPDoc for setValue? It's already specified on `FormField::setValue` and doesn't need to be redefined. It should inherit automatically.

File: forms/NumericField.php (hunk 3 above)
Comment (tractorcow) [inline forms/NumericField.php]: This is only public so that NumericFieldTest can access it. I could protect the method and just duplicate the logic in the test case. What do you think?

The behaviour of the Zend locale differs between php 5.3 and above, which means the expected input/outputs can't be hard coded. This method was created to fix failing test cases that only broke in 5.3.

Comment (tractorcow) [inline forms/NumericField.php]: Just to clarify, in some versions of PHP locale formatted numbers can have different unicode values used for the 'space' character, which makes unit testing problematic, since we can't have hard coded expected inputs/outputs. In this case, we just normalise all whitespaces for the sake of testing.

Comment (tractorcow) [inline forms/NumericField.php]: > It's also used inconsistently as static (in tests) and instance method (in IsNumeric).

Apparently it's fine (and not at all bad practice) to call static methods non-statically, only vice versa. We do this a lot with `Object::config`. :) It's like the negative margins of the backend dev world.

**Comment by tractorcow** [comment]
@chillu I've implemented your suggestion of making `clean` non-public API.

**Comment by dhensby** [comment]
bump @chillu

File: forms/NumericField.php [hunk 4]
```diff
@@ -2,13 +2,65 @@
...
+		return str_replace(' ', $nbsp, trim($input));
+	}
+	
+	/**
+	 * Determine if the current value is a valid number in the current locale
+	 * 
+	 * @param mixed $value Optional value to check against. Will check the current value if not given
+	 * @return bool
+	 */
+	public function IsNumeric($value = null) {
```
Comment (chillu) [inline forms/NumericField.php]: Why start this function with an uppercase? We have this weird rule in the coding conventions about UpperCamelCase for anything that's callable from a template, but that pretty much applies to all public methods. Also, I think allowing to pass in a `$value` is making the API too confusing (using it as a quasi-static checker). What's the reasoning for this?

Comment (tractorcow) [inline forms/NumericField.php]: Yeah I think you're right.

The use of this method is to short circuit formatting / evaluation if not in a valid format, and for validation.

I figured allowing it to take a variable would be useful for usercode which might want to ask if the field would accept a given value, but I guess we may as well just make it protected isNumeric()

Comment (tractorcow) [inline forms/NumericField.php]: Notice my $value = assignment without actually using the value... sorry. XD

**Comment by tractorcow** [comment]
@chillu Fixed!

**Comment by chillu** [comment]
Great, merged! Thanks for your persistence Damian :)

**Comment by tractorcow** [comment]
Yay thanks @chillu

**Comment by dhensby** [comment]
just in time :)
