### PR TITLE
BUG Fix writeBaseRecord with unique indexes

### LINKED ISSUE #6819: unique index / indexes are error prone
**Summary:**

Unique indexes are not such a good idea within the current Silverstripe set up (3.5.3), AFAIK, because they are prone to race conditions and other errors, making all future inserts impossible.  The reason for this is that `DataObject::write` carries out its writing in two steps. The first step writes an empty record to obtain an ID, the second (and further writes), add the data.  If the first write is performed and the second write crashes or whatever else can go wrong then the table can not be written to ever again (until the empty record is manually removed). 

----

When creating a unique index, you are likely to encounter problems due to the way SS inserts new records.  Please forgive me if I got it all wrong.  I have limited time to raise this ticket and I am not coding pro, but it may be worth noting. I have already raised this on the dev group (https://groups.google.com/forum/#!topic/silverstripe-dev/n-FZ8pSsWD8)

AFAIK Records (database rows) are written, 
1. firstly with creation date and ID only. 
2. with second write for any data.

This means that no records can be written to a table while any write process is between 1 and 2.  Sometimes this can be because of race-like conditions but it could also be the case that 2 does not happen because of faulty data, server failure, or whatever else you can imagine.

Here is the relevant code (from 3.5.3) in DataObject:

image

image

Line 1313 ... 1316 above executes a query:

image

call to DB::prepared_query:

image

and then to the connector:

image

The way I read this code is that `writeBaseRecord` actually inserts an empty record, after which further write(s) add the additional data.

Options (some of them a little crazy!):

* make this limitation clear in documentation OR
* add roll-back procedure to delete new entry in case of error OR
* disallow unique indexes as they do not work so well with Silvertripe ORM OR
* lock database row until full insert has been done (this will prevent race conditions I guess) OR
* refactor the whole system ;-) so that we insert the data with the original insert OR
* build a silverstripe specific way to deal with unique indexes that does not involve the DB itself
* ...

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #6819

I've had this bug in mind for years. This will fix the below bug once and for all:

```
Couldn't run query:

INSERT INTO "App_MemberRole"
 (\"Created\")
 VALUES
 (?)

Duplicate entry '0-0' for key 'OneMemberPerProperty'
```

This often came up when writing ChangesetItem due to the primary key being a composite on a couple of columns.

### CODE REVIEW

File: tests/php/ORM/DataObjectSchemaTest.php [hunk 1]
```diff
@@ -343,4 +343,35 @@ public function testFieldsCanBeIndexedFromFieldSpecs()
...
+            [
+                ['Number' => 0],
+            ],
+            AllIndexes::get()
+        );
+
+        // Test a new record can be created without clashing with default value
+        $validObjcet = new AllIndexes();
+        $validObjcet->Number = 1;
+        $validObjcet->write();
```
Comment (tractorcow) [inline tests/php/ORM/DataObjectSchemaTest.php]: Eh, I'll fix this in a second.

**Comment by tractorcow** [comment]
Interestingly this bug has been around as long as SilverStripe has.

https://github.com/silverstripe/silverstripe-framework/blob/2.1/core/model/DataObject.php#L432-L436

**Comment by tractorcow** [comment]
Oops, prepareManipulationTable assumes ID was set. A small tweak fixed that. :)

**Comment by dhensby** [comment]
Nice one @tractorcow! 🎉

**Comment by patricknelson** [comment]
I'm guessing in the example above `App_MemberRole` is actually a descendant of another `DataObject` correct? If so, then the reason why this fix works (i.e. checking `$this->isInDB() === true` first) is because you're actually writing a new record in a _child object's_ table, so the child object (who's `ID` must be synchronized with the parent object's table)  doesn't actually exist in the DB, which is **why** you're assigning the ID. As the code is written, it looks backwards, but it works because the `->ID` is indeed assigned because the _base_ record has in fact already been written and (naturally) an artifact of that is the the ID will not be zero and thus no duplicate errors.

It's more of a point on succinct semantics and reducing tech debt/legacy. Maybe a comment can be introduced here, like:


```php
        // Ensure we have an ID first and then synchronize ID's across child object records.
        if ($this->isInDB()) {
            $manipulation[$table]['id'] = $this->record['ID'];
        }
```

Or similar. I've proposed an explanation of an API level disambiguation on that nuance in https://github.com/silverstripe/silverstripe-framework/issues/8411#issuecomment-469422545

**Comment by tractorcow** [comment]
I would write something like `// Provide ID if generated for this record, otherwise leave blank to trigger a new auto-increment value`.

**Comment by robbieaverill** [comment]
@tractorcow the kitchen sink found some bugs that this introduced, I've made a tiny patch at https://github.com/silverstripe/silverstripe-framework/pull/8839 to fix that

**Comment by robbieaverill** [comment]
@tractorcow ignore me, actually some dodgy logic in the auditor module
