### PR TITLE
FIX: Graceful degradation if obsolete classnames in ChangeSetItem (fixes #6065)

### LINKED ISSUE #6065: ChangeSet referencing non-existent class prevents Campaigns view from loading
I noticed this because I had a ChangeSet referencing the 'SiteTree' class from before we namespaced the code.

If this happens, and you try and load the Campaigns view, the /admin/campaing/sets view gives the following error:

```
[Unknown Error] Uncaught ReflectionException: Class SiteTree does not exist
GET /ss4/admin/campaigns/sets
Line 178 in /Users/sminnee/Sites/ss4/framework/Core/ClassInfo.php
Source
169 	 * eg: self::class_name('dataobJEct'); //returns 'DataObject'
170 	 *
171 	 * @param string|object $nameOrObject The classname or object you want to normalise
172 	 * @return string The normalised class name
173 	 */
174 	public static function class_name($nameOrObject) {
175 		if (is_object($nameOrObject)) {
176 			return get_class($nameOrObject);
177 		}
178 		$reflection = new ReflectionClass($nameOrObject);
179 		return $reflection->getName();
180 	}
181 
182 	/**
183 	 * Returns the passed class name along with all its parent class names in an
184 	 * array, sorted with the root class first.
Trace
ReflectionClass->__construct(SiteTree) 
ClassInfo.php:178
SilverStripe\Core\ClassInfo::class_name(SiteTree) 
DataObjectSchema.php:118
SilverStripe\ORM\DataObjectSchema->baseDataClass(SiteTree) 
Versioned.php:2091
SilverStripe\ORM\Versioning\Versioned::get_versionnumber_by_stage(SiteTree,Stage,2,) 
ChangeSetItem.php:122
SilverStripe\ORM\Versioning\ChangeSetItem->getChangeType() 
ChangeSetItem.php:165
SilverStripe\ORM\Versioning\ChangeSetItem->findReferenced() 
ChangeSet.php:204
SilverStripe\ORM\Versioning\ChangeSet->calculateImplicit() 
ChangeSet.php:244
SilverStripe\ORM\Versioning\ChangeSet->SilverStripe\ORM\Versioning\{closure}() 
call_user_func(Closure) 
Database.php:544
SilverStripe\ORM\Connect\Database->withTransaction(Closure) 
ChangeSet.php:272
SilverStripe\ORM\Versioning\ChangeSet->sync() 
CampaignAdmin.php:261
SilverStripe\Admin\CampaignAdmin->getChangeSetResource(SilverStripe\ORM\Versioning\ChangeSet) 
CampaignAdmin.php:246
SilverStripe\Admin\CampaignAdmin->getListResource() 
CampaignAdmin.php:219
SilverStripe\Admin\CampaignAdmin->readCampaigns(SilverStripe\Control\HTTPRequest) 
RequestHandler.php:306
SilverStripe\Control\RequestHandler->handleAction(SilverStripe\Control\HTTPRequest,readCampaigns) 
Controller.php:284
SilverStripe\Control\Controller->handleAction(SilverStripe\Control\HTTPRequest,readCampaigns) 
RequestHandler.php:215
SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest,SilverStripe\ORM\DataModel) 
Controller.php:215
SilverStripe\Control\Controller->handleRequest(SilverStripe\Control\HTTPRequest,SilverStripe\ORM\DataModel) 
LeftAndMain.php:607
SilverStripe\Admin\LeftAndMain->handleRequest(SilverStripe\Control\HTTPRequest,SilverStripe\ORM\DataModel) 
AdminRootController.php:112
SilverStripe\Admin\AdminRootController->handleRequest(SilverStripe\Control\HTTPRequest,SilverStripe\ORM\DataModel) 
Director.php:433
SilverStripe\Control\Director::handleRequest(SilverStripe\Control\HTTPRequest,SilverStripe\Control\Session,SilverStripe\ORM\DataModel) 
Director.php:186
SilverStripe\Control\Director::direct(/admin/campaigns/sets,SilverStripe\ORM\DataModel) 
main.php:202
```

I think this is important for anyone upgrading alpha1 to alpha2. We could also fix it in the dev/build process if that were easier.

### PR DESCRIPTION
**Pull request by sminnee**
* FIX: Graceful degradation if obsolete classnames in ChangeSetItem (fixes #6065)
 * NEW: Add SilverStripe\ORM\UnexpectedDataException class.

----

This change provides more graceful handling of the case where a
ChangeSetItem is referencing a no-longer-existing class.

The new exception, SilverStripe\ORM\UnexpectedDataException, is
intended to be available for throwing whenever we have unexpected data
in the database.

It can be trapped by the relevant UIs and more graceful errors than
HTTP 500s can be provided.

### CODE REVIEW

File: admin/code/CampaignAdmin.php [hunk 1]
```diff
@@ -258,7 +259,21 @@ protected function getListResource() {
...
+				'ID' => $changeSet->ID,
+				'Name' => $changeSet->Name,
+				'Description' => 'Corrupt database! ' . $e->getMessage(),
+				'Created' => $changeSet->Created,
+				'LastEdited' => $changeSet->LastEdited,
+				'State' => $changeSet->State,
+				'canEdit' => $changeSet->canEdit(),
+				'canPublish' => false,
+				'_embedded' => ['items' => []]
+			];
```
Comment (flamerohr) [inline admin/code/CampaignAdmin.php]: there's a fair amount of duplicating with the `$hal` variable below

Comment (sminnee) [inline admin/code/CampaignAdmin.php]: Fair point @flamerohr I've DRYed it up a bit.
