### PR TITLE
FIX Confirmation components to respect SS_BASE_URL

### LINKED ISSUE #9061: 4.4.0 regression / ?flush does not respect SS_BASE_URL
## Affected Version

Silverstripe Version: 4.4.0 and 4.4.1
Wamp: 3.1.13
Apache: 2.4.33
PHP: 7.2.4
MySQL: 5.7.21
MariaDB: 10.2.14

## Description

Original description: https://forum.silverstripe.org/t/4-4-1-redirects-to-documentroot-instead-of-ss-base-url/1986

Question: Why do I get redirected to DocumentRoot instead of SS_BASE_URL, unlike previous versions?

After a successful install of SilverStripe 4.4.1, I get auto-redirected to DocumentRoot instead of the project’s base url. I can navigate back to the correct sub-directory and everything functions as normal.

This issue does not occur in versions 4.2.0, 4.3.0, and 4.3.3

My DocumentRoot is C:\wamp\www reachable at 127.0.0.1
Version 3.4.4 is in C:\wamp\www\344\ and is reachable at 127.0.0.1/334/
Version 4.4.1 is in C:\wamp\www\441\ and is reachable at 127.0.0.1/441/

They were obtained through composer like so:

```
C:\wamp\www>composer create-project silverstripe/installer 433 4.3.3
C:\wamp\www>composer create-project silverstripe/installer 441 4.4.1
```

My DocumentRoot’s index.php is a welcome page with links that takes you to either version.

The following illustrates each step in the installation process:

00da23ed36b4377c96bf01b9ce7bda5a2ba440cf
4.3.3 installs successfully and redirects correctly.

4.4.1 installs successfully but redirects to DocumentRoot. I manually type in the missing sub-directory to get to the last step.

## Notes

I would also like to note that if I do flush=all while not in dev mode, I get redirected to DocumentRoot and with a urlspecialstoken, but if I manually type in the missing sub-directory and with the provided urlspecialstoken, it will flush successfully.

## PRs

 - [x] https://github.com/silverstripe/silverstripe-framework/pull/9074

### PR DESCRIPTION
**Pull request by dnsl48**
Fixes #9061

### CODE REVIEW

File: src/Control/Middleware/ConfirmationMiddleware.php [hunk 1]
```diff
@@ -81,8 +82,15 @@ public function __construct(...$rules)
      */
     protected function getConfirmationUrl(HTTPRequest $request, $confirmationStorageId)
     {
+        $url = $this->confirmationFormUrl;
+
+        if (substr($url, 0, 1) === '/') {
```
Comment (robbieaverill) [inline src/Control/Middleware/ConfirmationMiddleware.php]: How about using `Director::is_absolute($url)`?

File: src/Security/Confirmation/Storage.php [hunk 2]
```diff
@@ -236,7 +238,8 @@ public function getItem($key)
      */
     public function setSuccessRequest(HTTPRequest $request)
     {
-        $this->setSuccessUrl($request->getURL(true));
+        $url = Controller::join_links(Director::baseURL(), $request->getURL(true));
```
Comment (robbieaverill) [inline src/Security/Confirmation/Storage.php]: Similar to above, I think you could probably use `Director::absoluteURL($request->getURL(true))` here

File: src/Control/Middleware/ConfirmationMiddleware.php (hunk 1 above)
Comment (dnsl48) [reply src/Control/Middleware/ConfirmationMiddleware.php]: ok, I've had a look and `Director::absoluteURL` is not what we can use here.

Apart from performing a lot of unnecessary extra checks, it also produces incorrect result because of the leading slash in the URL. Here's the [self::is_root_relative_url($url)](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Control/Director.php#L458) call, which makes it actually ignore the BASE_URL rather than enforcing it.

**Comment by dnsl48** [comment]
@robbieaverill sorry, I've rolled back the Director::absoluteURL use. It's not going to work with urls that begin with slash. On the other hand, we cannot rely on having relative URLs in the YML config for the middleware, because then we won't be able to use actual relative URLs there (that would introduce another bug). Sanitising it to suit the peculiar Director::absoluteURL logic doesn't feel right either.

File: src/Control/Middleware/ConfirmationMiddleware.php (hunk 1 above)
Comment (unclecheese) [reply src/Control/Middleware/ConfirmationMiddleware.php]: Might need to be `Director::absoluteURL($url, Director::REQUEST)`

Comment (dnsl48) [reply src/Control/Middleware/ConfirmationMiddleware.php]: yeah, unfortunately it's not going to work because of the [self::is_root_relative_url($url)](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Control/Director.php#L458) call

Comment (unclecheese) [reply src/Control/Middleware/ConfirmationMiddleware.php]: Agreed. 👍 

Can we flag this as an issue?

Comment (dnsl48) [reply src/Control/Middleware/ConfirmationMiddleware.php]: reported here - https://github.com/silverstripe/silverstripe-framework/issues/9111

**Comment by ScopeyNZ** [comment]
I'd really prefer we don't squash and commit these one commit PRs into framework :\ . It's really weird when you're trying to look at the commit that @dnsl48 authored not appearing any any tag (or branch) because the commit hash has been changed unnecessarily.

File: src/Control/Middleware/ConfirmationMiddleware.php (hunk 1 above)
Comment (tractorcow) [reply src/Control/Middleware/ConfirmationMiddleware.php]: @dnsl48 if your base url is `http://www.mysite.com/subfolder/` and `$url` is `/subfolder/page`, then you don't want the absolute url to end up as `http://www.mysite.com/subfolder/subfolder/page`. That's why the is_root_relative() is needed.

These are the same rules used by web browsers for url resolution; a leading `/` will force the url to resolve relative to the site root, but `subfolder/page` will resolve relative to either the current url, or base_url if that's set.

File: src/Security/Confirmation/Storage.php (hunk 2 above)
Comment (tractorcow) [reply src/Security/Confirmation/Storage.php]: Maybe we need $request->getAbsoluteURL()?

File: src/Control/Middleware/ConfirmationMiddleware.php (hunk 1 above)
Comment (tractorcow) [reply src/Control/Middleware/ConfirmationMiddleware.php]: > Apart from performing a lot of unnecessary extra checks, it also produces incorrect result because of the leading slash in the URL. Here's the self::is_root_relative_url($url) call, which makes it actually ignore the BASE_URL rather than enforcing it.

Where is this conformationFormUrl coming from? Maybe don't put a leading `/` on it if it's causing your issue?

Comment (dnsl48) [reply src/Control/Middleware/ConfirmationMiddleware.php]: >  if your base url is http://www.mysite.com/subfolder/ and $url is /subfolder/page, then you don't want the absolute url to end up as http://www.mysite.com/subfolder/subfolder/page.

I think this is a somewhat controversial assumption, depending on a particular use case rather than a general rule. In the particular scenario of this PR I'd actually would like to end up with `http://www.mysite.com/subfolder/subfolder/page`, because this is the correct result.

Comment (dnsl48) [reply src/Control/Middleware/ConfirmationMiddleware.php]: > Where is this conformationFormUrl coming from? Maybe don't put a leading / on it if it's causing your issue?

I'm not sure that would be semantically incorrect. As you mentioned above - a leading / will force the url to resolve relative to the site root, but subfolder/page will resolve relative to either the current url, or <base >. However, on the server side we don't have "documents" and as such if we treat everything as the same "document" with the <base href=SS_BASE_URL>, then we won't be able to use relative URLs there (relative to a page and not the global SS_BASE_URL).
