### PR TITLE
FIX SearchableDropdownTrait failing to filter empty values (fixes #11910)

### LINKED ISSUE #11910: SearchableMultiDropdownField can cause errors when submitted empty
### Module version(s) affected

5.4.22

### Description

I haven’t tested this on 6.x, but the code appears identical so I believe it will also be affected. I’ve also not tested `SearchableDropdownField` (the single value version) but believe it will be affected in the same way.

When a `SearchableMultiDropdownField` is submitted while empty, it passes an empty array as its value. I think this part is okay, as it’s an array-like field and it is empty. However, this results in a server-side value of a non-empty array: `array:1 [ 0 => 0 ]`.

The result of this is that when a DataObject is written, it attempts to save this value into a relationlist, which then errors because the object with an ID of `0` doesn’t exist. Specifically it hits [this exception](https://github.com/silverstripe/silverstripe-framework/blob/29c4bd738afad9e313faebf15f90f05365e26ee0/src/ORM/ManyManyList.php#L241) in `ManyManyList::add()`.

### How to reproduce

<details>
<summary>Sample DataObject</summary>

```php
<?php

namespace App\Model\Documents;

use SilverStripe\Forms\CompositeValidator;
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\RequiredFields;
use SilverStripe\Forms\SearchableMultiDropdownField;
use SilverStripe\Forms\TextField;
use SilverStripe\ORM\DataObject;
use SilverStripe\ORM\ManyManyList;

/**
 * @method ManyManyList Categories()
 */
class Document extends DataObject
{
    private static string $table_name = 'Document';

    private static array $db = [
        'Title' => 'Varchar(255)',
        'URL' => 'Text',
    ];

    private static array $belongs_many_many = [
        'Categories' => DocumentCategory::class,
    ];

    private static string $default_sort = 'LastEdited DESC';

    public function getCMSFields(): FieldList
    {
        $this->beforeUpdateCMSFields(function (FieldList $fields) {
            $fields->removeByName(['URL', 'Categories']);

            $fields->addFieldsToTab(
                'Root.Main',
                [
                    TextField::create('URL', 'URL')
                        ->setAttribute('placeholder', 'https://'),
                    SearchableMultiDropdownField::create('Categories', 'Categories', DocumentCategory::get()),
                ]
            );
        });

        return parent::getCMSFields();
    }

    public function getCMSCompositeValidator(): CompositeValidator
    {
        return parent::getCMSCompositeValidator()->addValidator(RequiredFields::create([
            'URL',
        ]));
    }
}

```
</details>

<details>
<summary>Sample related DataObject</summary>

```php
<?php

namespace App\Model\Documents;

use SilverStripe\ORM\DataObject;
use SilverStripe\ORM\ManyManyList;

/**
 * @method ManyManyList Documents()
 */
class DocumentCategory extends DataObject
{
    private static string $table_name = 'DocumentCategory';

    private static array $db = [
        'Title' => 'Varchar(255)',
    ];

    private static array $many_many = [
        'Documents' => Document::class,
    ];
}

```
</details>

<details>
<summary>Sample ModelAdmin</summary>

```php
<?php

namespace App\Admin;

use App\Model\Documents\Document;
use SilverStripe\Admin\ModelAdmin;

class DocumentsAdmin extends ModelAdmin
{
    private static array $managed_models = [
        Document::class,
        DocumentCategory::class,
    ];

    private static string $menu_title = 'Documents';

    private static string $menu_icon_class = 'font-icon-install';

    private static string $url_segment = 'documents';
}

```
</details>

- Add the code samples
- Create a couple of test document categories
- Create a new `Document` record
- Fill out the title/URL, leave categories blank, click save

### Possible Solution

Call `array_filter()` on the value while building it in `SearchableDropdownTrait`

### Additional Context

_No response_

### Validations

- [x] Check that there isn't already an issue that reports the same bug
- [x] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs

- https://github.com/silverstripe/silverstripe-framework/pull/11911

### PR DESCRIPTION
**Pull request by lozcalver**
## Description
Fix for #11910. Re-arranged test data provider to put all the “empty” value tests next to each other

## Manual testing steps
See reproduction steps in #11910

## Issues

- #11910

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [x] CI is green

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Since this is a bug for CMS 5.4 according to the linked issue, and that is still in support for bug fixes, can you please retarget this PR to the `5.4` branch? You may need to [reset your commits](https://gist.github.com/GuySartorelli/74627843aeb75e12b777b1f44cb22d2f) after retargetting.

**Comment by lozcalver** [comment]
Oops. I branched off 5.4 but forgot to update the base when opening the PR!

**Comment by lozcalver** [comment]
No idea what’s going on with the single failed job. Tried restarting it but same error, looks like a temporary blip

**Comment by GuySartorelli** [comment]
> No idea what’s going on with the single failed job. Tried restarting it but same error, looks like a temporary blip

That's very strange - normally those fix themselves after a restart. But in any case those specific tests won't be affected by the changes in this PR so I'm happy to ignore that for the purposes of this PR.

File: tests/php/Forms/SearchableDropdownTraitTest.php [hunk 1]
```diff
@@ -168,6 +168,18 @@ public function provideGetValueArray(): array
...
+            ],
+            'array - empty string' => [
+                'value' => [''],
+                'expected' => [],
+            ],
+            'array - zero string' => [
+                'value' => ['0'],
+                'expected' => [],
+            ],
         ];
```
Comment (GuySartorelli) [inline tests/php/Forms/SearchableDropdownTraitTest.php:191]: What happens if the value is `[1]` or `['1']`?

**Review by GuySartorelli — COMMENTED** [review]
Seems fine, just one question that the new test cases bring up

File: tests/php/Forms/SearchableDropdownTraitTest.php (hunk 1 above)
Comment (lozcalver) [reply tests/php/Forms/SearchableDropdownTraitTest.php:191]: I’ve pushed a couple of new values to the data provider to find out 😉

**Review by GuySartorelli — APPROVED** [review]
LGTM, thank you for submitting this
