### PR TITLE
BUG Fix false values for many_many_ExtraFields not being saved

### LINKED ISSUE #4067: [Bug] Can't save an unchecked checkbox for a boolean in a many_many_extraField
I've got an object called `Account` which has a `many_many` to `Users`. `Account` has the following `many_many_extraFields`:

```
private static $many_many_extraFields = array(
	'Users' => array(
		'CanRead' => 'Boolean',
		'CanModify' => 'Boolean',
		'CanManage' => 'Boolean',
		'Note' => 'Varchar'
	)
);
```

I am using the following code to show these options when navigating that relationship via GridField:

```
$usersGridFieldConfig = $fields->fieldByName('Root.Users.Users')->getConfig();

$usersExtraFields = new FieldList();
$usersExtraFields->push(CheckboxField::create(
	'ManyMany[CanRead]',
	'Can Read'
));

$usersGridFieldConfig->getComponentByType('GridFieldDetailForm')->setFields($usersExtraFields);
```

So far so good, the field will appear when navigating the relationship just how I wanted. When checking the checkbox and pressing save, that correctly saves to the DB (confirmed when manually checking the DB and the checkbox appears checked when loaded).

When I now uncheck the checkbox and press save, it says the save is successful however neither the DB or field itself is updated.

I have checked with the "Note" extra field by setting a value, saving and then blanking it and that doesn't cause any issues. Also added another extra field with the Int data type, no issues setting various values for that.

I have also double checked my code against [the example of `many_many_extraFields` in the documentation](http://doc.silverstripe.org/en/developer_guides/forms/field_types/gridfield#many-many-extrafields) and I don't see anything I am doing that would be particularly wrong.

This is with Framework and CMS 3.1.x-dev (updated yesterday). No errors are shown, just doesn't save that field's value. Not sure if this is possibly related to #1664 as well.

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #4067 

This is because the $extraData was extracted directly from the posted data, when the correct way to retrieve data is to rely on the result of Form::saveInto, as this is how fields such as CheckboxField are able to overwrite values with false if no data is posted.

### CODE REVIEW

File: model/ManyManyList.php [hunk 1]
```diff
@@ -230,37 +230,29 @@ public function add($item, $extraFields = array()) {
...
-				$manipulation[$this->joinTable]['command'] = 'update';
 				$manipulation[$this->joinTable]['where'] = array(
 					"\"{$this->joinTable}\".\"{$this->foreignKey}\"" => $foreignID,
 					"\"{$this->joinTable}\".\"{$this->localKey}\"" => $itemID
 				);
-			} else {
-				$manipulation[$this->joinTable]['command'] = 'insert';
 			}
 
-			if($extraFields) {
```
Comment (tractorcow) [inline model/ManyManyList.php]: The existing code was trying to hack in custom manipulations, and it was breaking on sqlite3, so I simply took the code from DataObject and ensured it used the same method.

File: forms/gridfield/GridFieldDetailForm.php [hunk 2]
```diff
@@ -495,21 +495,38 @@ protected function getBackLink(){
 
 		return $backlink;
 	}
-
-
+	
+	/**
+	 * Get the list of extra data from the $record as saved into it by
+	 * Form::savInto
```
Comment (assertchris) [inline forms/gridfield/GridFieldDetailForm.php]: Typo

File: forms/gridfield/GridFieldDetailForm.php [hunk 3]
```diff
@@ -495,21 +495,38 @@ protected function getBackLink(){
...
+	 * 
+	 * Handles detection of falsey values explicitly saved into the
+	 * DataObject by formfields
+	 * 
+	 * @param DataObject $record
+	 * @param SS_List $list
```
Comment (assertchris) [inline forms/gridfield/GridFieldDetailForm.php]: No @return

File: forms/gridfield/GridFieldDetailForm.php (hunk 2 above)
Comment (tractorcow) [inline forms/gridfield/GridFieldDetailForm.php]: You mean, so I've got nothing to fix later? Ok. =(

**Comment by tractorcow** [comment]
Fixed based on your feedback @assertchris

**Comment by tractorcow** [comment]
@dhensby want to look at this while you're reviewing stuff for 3.2?

**Comment by tractorcow** [comment]
Ta :D

**Comment by gordonbanderson** [comment]
This bug still appears to exist in 3.1.15.  I've just into it, Checkboxes are only being saved if their value is true.

**Comment by tractorcow** [comment]
Yep. :D Users will need to upgrade to 3.2.0 to get this fix.

**Comment by gordonbanderson** [comment]
I tried to work around this using a PickerField module, which turned out to have the same issue.  However it was possible to fix it there, and this offers a workaround for 3.1 users https://github.com/briceburg/silverstripe-pickerfield/pull/14#issuecomment-152885148
