### PR TITLE
FIX Add quotes to constants in YAML to ensure syntax validity

### LINKED ISSUE #6574: [4.0] "Reserved indicator ` cannot start a plain scalar" on Travis CI builds for a module
A recent Travis build using the latest master branch of the framework failed to parse configuration:

```
PHP Fatal error:  Uncaught exception 'Symfony\Component\Yaml\Exception\ParseException' with message 'The reserved indicator "`" cannot start a plain scalar; you need to quote the scalar at line 34 (near "2: `TEMP_FOLDER`").' in phar:///home/travis/build/silverleague/silverstripe-logviewer/phpunit/symfony/yaml/Inline.php:321
Stack trace:
#0 phar:///home/travis/build/silverleague/silverstripe-logviewer/phpunit/symfony/yaml/Inline.php(107): Symfony\Component\Yaml\Inline::parseScalar('`TEMP_FOLDER`', 0, NULL, Array, 13, true, Array)
#1 phar:///home/travis/build/silverleague/silverstripe-logviewer/phpunit/symfony/yaml/Parser.php(598): Symfony\Component\Yaml\Inline::parse('`TEMP_FOLDER`', 0, Array)
#2 phar:///home/travis/build/silverleague/silverstripe-logviewer/phpunit/symfony/yaml/Parser.php(261): Symfony\Component\Yaml\Parser->parseValue('`TEMP_FOLDER`', 0, 'mapping')
#3 phar:///home/travis/build/silverleague/silverstripe-logviewer/phpunit/symfony/yaml/Parser.php(354): Symfony\Component\Yaml\Parser->parse('0: 'en'\n1: null...', 0 in phar:///home/travis/build/silverleague/silverstripe-logviewer/phpunit/symfony/yaml/Inline.php on line 321
```

The line was probably added in #6558.

I can't reproduce this locally, but it happens consistently on Travis.

### PR DESCRIPTION
**Pull request by robbieaverill**
Resolves #6574

I didn't add a PHPUnit 5.7 build just yet.

### CODE REVIEW

File: src/Core/Injector/Injector.php [hunk 1]
```diff
@@ -525,8 +525,8 @@ public function convertServiceProperty($value)
             return $this->get($id);
         }
 
-        // Evaluate constants surrounded by back ticks
-        if (preg_match('/^`(?<name>[^`]+)`$/', $value, $matches)) {
+        // Evaluate constants surrounded by back ticks (and quotes)
+        if (preg_match('/^[\'"]?`(?<name>[^`]+)`[\'"]?$/', $value, $matches)) {
```
Comment (tractorcow) [inline src/Core/Injector/Injector.php]: If you quote the yml string it will come out unquoted when parsed by the yml parser. You shouldn't be looking for an extra layer of quotes here.

Comment (robbieaverill) [inline src/Core/Injector/Injector.php]: True! D'oh!

**Comment by tractorcow** [comment]
Can merge on green.

**Comment by kinglozzer** [comment]
LGTM 👍
