### PR TITLE
FIX DataObject singleton creation

### LINKED ISSUE #4878: populateDefaults not working on extensions
It seems, extending SiteConfig with a file and having a populate defaults breaks the build because SiteConfig is setup before File?

### PR DESCRIPTION
**Pull request by sminnee**
Ensure DataObject instances are aware they are singletons so functions like populateDefaults() can be skipped. (fixes #4878)

Correctly applies https://github.com/silverstripe/silverstripe-framework/pull/7850 to the 4.x line
This has already been fixed in 3.x

### CODE REVIEW

File: src/Core/Injector/Injector.php [hunk 1]
```diff
@@ -581,6 +582,11 @@ protected function instantiate($spec, $id = null, $type = null)
             $constructorParams = $spec['constructor'];
         }
 
+        // If we're dealing with a DataObject, pass through Singleton flag as second argument
+        if ($type != 'prototype' && empty($constructorParams) && is_subclass_of($class, DataObject::class)) {
```
Comment (unclecheese) [inline src/Core/Injector/Injector.php]: Strict comparison, please. Also use the provided constant (`self::PROTOTYPE`)

**Comment by chillu** [comment]
Tentatively marking as 4.3, assuming it's nearly over the line. This is the issue where every first dev build on a migrated data set fails in certain situations, making for a pretty crap onboarding experience to our platforms, right?

**Comment by sminnee** [comment]
@unclecheese @chillu if this is merged to the 4.1 branch today, will it make it into the 4.3 release? Or should I rebase this to a different branch?

File: src/Core/Injector/Injector.php (hunk 1 above)
Comment (sminnee) [reply src/Core/Injector/Injector.php]: Fixed. Also checked for !$type, as that's interpreted as singleton elsewhere.
