### PR TITLE
ENH allow stacked messages on FormMessage

### LINKED ISSUE #10270: Show all failed password criteria when changing a password to a not-strong-enough value
## Affected Version

4.10

## Description

I've just added a robust password policy to my site (yay me). When I attempt to set my password to "test" I am warned that:

`Please increase password strength by adding some of the following characters: uppercase, digits, punctuation`

which is fine, but then when I do I get:

`Password is too short, it must be 10 or more characters long`

which is super annoying. It would be much better to flag all the password failures at once, please.

## Steps to Reproduce

Add the following password requirements via yaml:

```yml
---
Name: app-passwords
After: '#corepasswords'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\PasswordValidator:
    properties:
      MinLength: 10
      MinTestScore: 3
```
Then attempt to set a password of "test", followed by a password of "Test1!"

## PR

- [ ] https://github.com/silverstripe/silverstripe-framework/pull/10966

### PR DESCRIPTION
**Pull request by andrewandante**
Fixes #10270 

Adds a new method: `FormMessage::appendMessage()` which attempts to stack messages if it can, falling back to the current behaviour of setting the message if there's a mismatch.

image

### CODE REVIEW

File: src/Forms/FormMessage.php [hunk 1]
```diff
@@ -92,6 +91,30 @@ public function setMessage(
...
+        string $messageCast = ValidationResult::CAST_TEXT,
+    ): static {
+        if (!empty($this->message)) {
+            $canBeMerged = ($messageType === $this->getMessageType() && $messageCast === $this->getMessageCast());
+            // Checks that the exact message string is not already contained before appending
+            if ($canBeMerged && strpos($this->message, $message) === false) {
+                $message = sprintf(
+                    '%s%s%s',
+                    $this->message,
+                    $messageType === ValidationResult::CAST_HTML ? '<br />' : PHP_EOL,
```
Comment (GuySartorelli) [inline src/Forms/FormMessage.php]:
```suggestion
                    $messageCast === ValidationResult::CAST_HTML ? '<br />' : PHP_EOL,
```

Also, what happens if someone changes the cast in some `FormField` or injected `Form` by changing the value of `$messageCast` after the message is appended?

File: src/Forms/FormMessage.php [hunk 2]
```diff
@@ -92,6 +91,30 @@ public function setMessage(
...
+     */
+    public function appendMessage(
+        string $message,
+        string $messageType = ValidationResult::TYPE_ERROR,
+        string $messageCast = ValidationResult::CAST_TEXT,
+    ): static {
+        if (!empty($this->message)) {
+            $canBeMerged = ($messageType === $this->getMessageType() && $messageCast === $this->getMessageCast());
+            // Checks that the exact message string is not already contained before appending
+            if ($canBeMerged && strpos($this->message, $message) === false) {
```
Comment (GuySartorelli) [inline src/Forms/FormMessage.php]: I feel like if it can't be merged, we should probably throw an exception rather than overriding the existing message.

**Review by GuySartorelli — CHANGES_REQUESTED** [review]

**Comment by GuySartorelli** [comment]
Also FYI this has prompted me to make [this issue for CMS 6](https://github.com/silverstripe/silverstripe-framework/issues/10967)

File: src/Forms/FormMessage.php (hunk 2 above)
Comment (andrewandante) [reply src/Forms/FormMessage.php]: Yeah there's merit to that. Maybe a "force" flag that overrides if set, throws if not?

File: src/Forms/FormMessage.php (hunk 1 above)
Comment (andrewandante) [reply src/Forms/FormMessage.php]: Good question - that's currently a possibility, right? You could set an HTML message and then change the cast, is that a problem we want to solve here?

I can see adding some `nl2br()`-style logic into `setMessageCast()` but that feels outside the scope

**Comment by andrewandante** [comment]
> Also FYI this has prompted me to make [this issue for CMS 6](https://github.com/silverstripe/silverstripe-framework/issues/10967)

Hah yes that was definitely coming, I was reluctant to turn this into an API-breaking change but I think that would definitely be the best long-term approach.

File: src/Forms/FormMessage.php (hunk 2 above)
Comment (GuySartorelli) [reply src/Forms/FormMessage.php]: Yeah that would be acceptable I think. At least then it's a clear and explicit decision developers are making to override the existing message if theirs doesn't match the existing type or casting.

File: src/Forms/FormMessage.php (hunk 1 above)
Comment (GuySartorelli) [reply src/Forms/FormMessage.php]: > You could set an HTML message and then change the cast, is that a problem we want to solve here?

It's the (potential) problem I'm pointing out, but I'm not sure if we need to solve it, or if we should just be aware of it and accept that people doing weird things will have weird results.

Probably the fact that we don't have a setter method for it is enough to say "we don't support changing that property directly", and in that case what you have here is good.

**Comment by andrewandante** [comment]
Think I've managed to get my conditions in the right order now 😅

File: src/Forms/Form.php
Comment (GuySartorelli) [inline src/Forms/Form.php:1]: We should probably update the note in the PHPDoc for this method
```diff
- Note: This will not clear any pre-existing messages
+ Note: This will try to not clear any pre-existing messages, but will clear them if a new message has a different message type than the existing ones.
```

File: src/Forms/FormMessage.php [hunk 3]
```diff
@@ -92,6 +91,57 @@ public function setMessage(
         return $this;
     }
 
+    /**
+     * Appends a message to the existing message if the types match, overrides if not
```
Comment (GuySartorelli) [inline src/Forms/FormMessage.php]:
```suggestion
     * Appends a message to the existing message if the types match.
     * If the type or cast is different, the $force argument controls what happens
```

File: src/Forms/FormMessage.php [hunk 4]
```diff
@@ -92,6 +91,57 @@ public function setMessage(
...
+     *
+     * @param string $message Message string
+     * @param string $messageType Message type
+     * @param string $messageCast
+     * @param bool $force Whether or not to override the existing message if appending is invalid
+     * @throws InvalidArgumentException
+     * @return $this
```
Comment (GuySartorelli) [inline src/Forms/FormMessage.php]:
```suggestion
     * @param bool $force Whether or not to override the existing message if appending is invalid
     * @throws InvalidArgumentException
```
We don't need to mention the return type or parameters in the PHPDoc unless they add additional context. Having them there increases the chance that they'll become desynced with the actual typehint.

File: src/Forms/FormMessage.php [hunk 5]
```diff
@@ -92,6 +91,57 @@ public function setMessage(
...
     }
 
+    /**
+     * Appends a message to the existing message if the types match, overrides if not
+     *
+     * @param string $message Message string
+     * @param string $messageType Message type
+     * @param string $messageCast
+     * @param bool $force Whether or not to override the existing message if appending is invalid
+     * @throws InvalidArgumentException
```
Comment (GuySartorelli) [inline src/Forms/FormMessage.php]:
```suggestion
     * @throws InvalidArgumentException if $force is false and the new message type or cast differs from the existing ones.
```

File: src/Forms/FormMessage.php [hunk 6]
```diff
@@ -92,6 +91,57 @@ public function setMessage(
         return $this;
     }
 
+    /**
+     * Appends a message to the existing message if the types match, overrides if not
+     *
+     * @param string $message Message string
+     * @param string $messageType Message type
+     * @param string $messageCast
+     * @param bool $force Whether or not to override the existing message if appending is invalid
```
Comment (GuySartorelli) [inline src/Forms/FormMessage.php]:
```suggestion
     * @param bool $force If true, and the new message cannot be appended to the existing one, the existing message will be overridden.
```

File: src/Forms/FormMessage.php [hunk 7]
```diff
@@ -92,6 +91,57 @@ public function setMessage(
...
+    public function appendMessage(
+        string $message,
+        string $messageType = ValidationResult::TYPE_ERROR,
+        string $messageCast = ValidationResult::CAST_TEXT,
+        bool $force = false,
+    ): static {
+        if (empty($this->message)) {
+            return $this->setMessage($message, $messageType, $messageCast);
+        }
+        $canBeMerged = ($messageType === $this->getMessageType() && $messageCast === $this->getMessageCast());
```
Comment (GuySartorelli) [inline src/Forms/FormMessage.php:118]:
```suggestion

        $canBeMerged = ($messageType === $this->getMessageType() && $messageCast === $this->getMessageCast());
```

File: src/Forms/FormMessage.php [hunk 8]
```diff
@@ -92,6 +91,57 @@ public function setMessage(
...
+
+        if (!$canBeMerged && $force === false) {
```
Comment (GuySartorelli) [inline src/Forms/FormMessage.php]:
```suggestion
        if (!$canBeMerged && !$force) {
```
These are both bool - so either they both get `=== false` treatment or they both get `!` treatment. Having them differ makes it look like one of them can be something other than bool, or for whatever reason needs to be treated specially.

File: src/Forms/FormMessage.php [hunk 9]
```diff
@@ -92,6 +91,57 @@ public function setMessage(
...
+     * @throws InvalidArgumentException
+     * @return $this
+     */
+    public function appendMessage(
+        string $message,
+        string $messageType = ValidationResult::TYPE_ERROR,
+        string $messageCast = ValidationResult::CAST_TEXT,
+        bool $force = false,
+    ): static {
+        if (empty($this->message)) {
```
Comment (GuySartorelli) [inline src/Forms/FormMessage.php:114]: We should also have an early check for if `empty($message)` - and if so, just return. It protects us from accidentally overriding an existing message with an _empty_ message if the message type and cast differ from the existing one.

File: src/Forms/FormMessage.php [hunk 10]
```diff
@@ -92,6 +91,57 @@ public function setMessage(
...
+                    $this->getMessageCast(),
+                )
+            );
+        }
+
+        // Checks that the exact message string is not already contained before appending
+        $messageContainsString = strpos($this->message, $message) !== false;
+        if ($canBeMerged && $messageContainsString) {
+            return $this;
+        }
```
Comment (GuySartorelli) [inline src/Forms/FormMessage.php:136]: Can you please explain why you want to add this? It could potentially result in unexpectedly not including messages that the developer wants to include if an existing message has it as a part of its message.

File: src/Forms/FormMessage.php [hunk 11]
```diff
@@ -92,6 +91,57 @@ public function setMessage(
...
+
+        if ($canBeMerged) {
+            $message = sprintf(
+                '%s%s%s',
+                $this->message,
+                $messageCast === ValidationResult::CAST_HTML ? '<br />' : PHP_EOL,
+                $message
+            );
```
Comment (GuySartorelli) [inline src/Forms/FormMessage.php]: I think concatenation or implode are more readable in this scenario

**Concatenation:**
```suggestion
            $separator = $messageCast === ValidationResult::CAST_HTML ? '<br />' : PHP_EOL;
            $message = $this->message . $separator . $message;
```

**Implode:**
```suggestion
            $separator = $messageCast === ValidationResult::CAST_HTML ? '<br />' : PHP_EOL;
            $message = implode($separator, [$this->message, $message]);
```

File: tests/php/Forms/FormTest.php
Comment (GuySartorelli) [inline tests/php/Forms/FormTest.php:1]: Can you please refactor the tests to use `@dataProvider`?

It ends up being easier to see what's being tested, and it also tests all scenarios even if one fails, which means if multiple would fail we can see them all failing and resolve them all in one pass instead of fixing one, only for the next one to fail when we run tests again.

Happy to provide guidance if you've not done it that way before, but searching for `@dataProvider` in the existing tests should give some fairly clear examples.

**Review by GuySartorelli — CHANGES_REQUESTED** [review]

File: src/Forms/FormMessage.php (hunk 10 above)
Comment (andrewandante) [reply src/Forms/FormMessage.php:136]: In testing I was seeing duplicate messages when entering a password that didn't meet the criteria. I didn't look into it _too_ much, but my general feeling was that without a major refactor (a la #10967) I couldn't effectively prevent duplicates. (actually thinking about this while I'm typing, I might "just" be able to use `array_unique()` on a private property 🤔  - will try that for a bit)

My theory (didn't go too deep) was that more than one thing was calling `validate()` on the `Member` record on `save()` - my guess would be the form handler and in `onBeforeWrite()`. That probably feels like a thing we could fix too but I didn't want to go too deep down the rabbit hole.

Filtering for unique messages in `Form::loadMessagesFrom()` didn't help because it was actually two separate calls.

Comment (GuySartorelli) [reply src/Forms/FormMessage.php:136]: Ahh yup that's fair enough.
I'd say don't spend too much time trying to find a cleaner solution - I'd be satisfied with a note in the PHPDoc about this limitation (so at least it's documented) and it can be solved more fully in a future major release (#10967).

File: src/Forms/FormMessage.php (hunk 8 above)
Comment (andrewandante) [reply src/Forms/FormMessage.php]: Hah yeah not sure how that ended up like that 😅

File: src/Forms/FormMessage.php (hunk 11 above)
Comment (andrewandante) [reply src/Forms/FormMessage.php]: I chooooooooooose concat 😄

File: tests/php/Forms/FormTest.php [hunk 12]
```diff
@@ -1030,6 +1097,54 @@ public function testFieldMessageEscapeHtml()
         );
     }
 
+    /**
+     * @dataProvider formMessageDataProvider
+     */
+    public function testFieldMessageAppend($messages)
```
Comment (GuySartorelli) [inline tests/php/Forms/FormTest.php:1103]:
```suggestion
    public function testFieldMessageAppend(array $message1, array $message2, bool $force = false)
```
Your data provider is passing in the arguments like this, which is why CI is unhappy. You could either refactor your dataprovider, or update this method to use this signature.
I think this ends up being tidier.

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
Looking good. Just need to make CI happy now. There's a suggestion below about making the phpunit job happy, and the lint job I think speak for itself.

**Review by GuySartorelli — APPROVED** [review]
Looks great and does what it says on the tin. Thanks!

**Comment by GuySartorelli** [comment]
This will be included in the Silverstripe CMS 5.2.0 release.
