### PR TITLE
Fix support for setting TEMP_PATH in .env (fixes #8099)

### LINKED ISSUE #8099: Setting a path (e.g. TEMP_PATH) in the .env file outputs into the public folder
## Affected Version

4.1.1

## Description

When setting TEMP_PATH to e.g. "silverstripe-cache" in the .env file, the cache folder is created inside the public folder instead of the base path.
`TEMP_PATH="silverstripe-cache"`

Expected:
`/path/to/silverstripe/silverstripe-cache`
Output:
`/path/to/silverstripe/public/silverstripe-cache`

Is this the expected output? If yes, is there another way to set the cache folder to the root path instead of using a rather "hacky" ../silverstripe-cache? Because defining it in the _config.php throws an error that it's already defined.

## Steps to Reproduce

- Use public folder structure.
- Set e.g. TEMP_PATH in .env file

### PR
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/10138

### PR DESCRIPTION
**Pull request by kinglozzer**
Proposed fix for #8099. I’ve opted to rename the variable to `SS_TEMP_PATH` for two reasons:

1. It fits the convention, and `TEMP_PATH` as an environment variable is currently broken anyway
2. It won’t conflict with the `TEMP_PATH` PHP constant in Injector service definitions that use ``'`TEMP_PATH`'``

### CODE REVIEW

File: src/Core/CoreKernel.php [hunk 1]
```diff
@@ -497,7 +497,7 @@ protected function buildManifestCacheFactory()
     {
         return new ManifestCacheFactory([
             'namespace' => 'manifestcache',
-            'directory' => TempFolder::getTempFolder($this->basePath),
+            'directory' => TEMP_PATH
```
Comment (michalkleiner) [inline src/Core/CoreKernel.php:500]:
```suggestion
            'directory' => TEMP_PATH,
```

**Comment by michalkleiner** [comment]
Looks sensible. Probably need to target `4` I'd say?

**Comment by kinglozzer** [comment]
Yeah I wasn’t sure about the target branch. It’s a documented feature and it doesn’t work properly, so I opted to treat it as a bugfix even though it’s technically introducing a new environment variable.

**Comment by michalkleiner** [comment]
@emteknetnz what's your opinion here, please?

**Comment by emteknetnz** [comment]
Target `4` since it's new configuration

@kinglozzer Would you be able to write a quick explanation for the 4.10 [changelog](https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/04_Changelogs/4.10.0.md)

Include support for releative/absolute paths, a little rationale behind this decision, as well as any potential gotchas

**Comment by kinglozzer** [comment]
I’ve added some more documentation and rebased against `4`

File: docs/en/04_Changelogs/4.10.0.md [hunk 2]
```diff
@@ -6,6 +6,14 @@
 
 ### Other new features
 
+#### New `SS_TEMP_DIR` environment variable
```
Comment (emteknetnz) [inline docs/en/04_Changelogs/4.10.0.md:9]: Should this be SS_TEMP_PATH? (not SS_TEMP_DIR)

File: src/includes/constants.php [hunk 3]
```diff
@@ -197,7 +197,15 @@
...
-    if (defined('TEMP_FOLDER')) {
+    // Check if path has been set in environment variables
+    if ($path = Environment::getEnv('SS_TEMP_PATH')) {
+        // If path is relative, rewrite it to be relative to BASE_PATH - as web requests are relative to
+        // public/index.php, and we don't want the TEMP_PATH to be inside the public/ directory by default
+        if (ltrim($path, DIRECTORY_SEPARATOR) === $path) {
+            $path = BASE_PATH . DIRECTORY_SEPARATOR . $path;
+        }
+        define('TEMP_PATH', $path);
+    } elseif (defined('TEMP_FOLDER')) {
```
Comment (emteknetnz) [inline src/includes/constants.php:208]: TEMP_FOLDER should still have higher precedence of SS_TEMP_PATH since it's an old alias for TEMP_PATH?

Seems slightly less likely to break existing setups if TEMP_FOLDER is read first

File: src/includes/constants.php [hunk 4]
```diff
@@ -15,9 +15,9 @@
  * - BASE_URL: Full URL to the webroot, e.g. "http://my-host.com/my-webroot" (no trailing slash).
  * - BASE_PATH: Absolute path to the webroot, e.g. "/var/www/my-webroot" (no trailing slash).
  *   See Director::baseFolder(). Can be overwritten by Config::modify()->set(Director::class, 'alternate_base_folder', ).
- * - TEMP_PATH: Absolute path to temporary folder, used as base for $TEMP_FOLDER. Example: "/var/tmp"
- * - TEMP_FOLDER: folder name for manifest and template caches. Example: "silverstripe-cache-php7.2"
- *   See getTempFolder(). No trailing slash.
+ * - TEMP_PATH: Path to temporary folder for manifest and template caches. May be relative to project root or an
```
Comment (emteknetnz) [inline src/includes/constants.php:18]: Should we mention SS_TEMP_PATH here as well? (possibly not?)

File: docs/en/04_Changelogs/4.10.0.md [hunk 5]
```diff
@@ -6,6 +6,14 @@
...
+
```
Comment (emteknetnz) [inline docs/en/04_Changelogs/4.10.0.md:10]: Seems like we should mention that any existing TEMP_PATH/TEMP_FOLDER environment variables will still be respected (I'm assuming that you can just set those)

File: docs/en/04_Changelogs/4.10.0.md [hunk 6]
```diff
@@ -6,6 +6,14 @@
...
+This release adds support for a new `SS_TEMP_DIR` environment variable, which allows developers to control where a series of “temporary” files are created. These include [Manifests](/developer_guides/execution_pipeline/manifests), [Object Caching](/developer_guides/performance/caching) and [Partial Template Caching](/developer_guides/templates/partial_template_caching).
+
+The environment variable can be set to either an absolute path which must have a leading `/` (e.g. `SS_TEMP_DIR='/tmp/silverstripe/cachedir'`), or a path relative to the project root (e.g. `SS_TEMP_DIR='silverstripe-cache'`). See the [environment management](/getting_started/environment_management) section for more information.
```
Comment (emteknetnz) [inline docs/en/04_Changelogs/4.10.0.md:13]: Need to update the 3x SS_TEMP_DIR to SS_TEMP_PATH

**Review by emteknetnz — CHANGES_REQUESTED** [review]

File: docs/en/04_Changelogs/4.10.0.md [hunk 7]
```diff
@@ -6,6 +6,14 @@
 
 ### Other new features
 
+#### New `SS_TEMP_DIR` environment variable
+
+This release adds support for a new `SS_TEMP_DIR` environment variable, which allows developers to control where a series of “temporary” files are created. These include [Manifests](/developer_guides/execution_pipeline/manifests), [Object Caching](/developer_guides/performance/caching) and [Partial Template Caching](/developer_guides/templates/partial_template_caching).
```
Comment (emteknetnz) [inline docs/en/04_Changelogs/4.10.0.md:11]: Should mention why we're doing this i.e. the TEMP_PATH/TEMP_FOLDER constants when set as env variables break in xyz scenarios

File: src/includes/constants.php (hunk 3 above)
Comment (kinglozzer) [reply src/includes/constants.php]: I’ve swapped these around so `TEMP_FOLDER` takes priority as before

File: src/includes/constants.php (hunk 4 above)
Comment (kinglozzer) [reply src/includes/constants.php:18]: Have added a small note about the new environment variable here

**Review by michalkleiner — APPROVED** [review]
It's a tick from me, but @emteknetnz has the lead here.

File: docs/en/04_Changelogs/4.10.0.md [hunk 8]
```diff
@@ -6,6 +6,18 @@
...
+
+**Please note:** setting this environment variable will impact both requests served by a webserver (i.e. a typical website pageview) and command-line execution. If your webserver user and command-line user are different, or have different filesystem permissions, you may encounter problems when using this setting.
+
+The new `SS_TEMP_PATH` environment variable replaces the similarly-named `TEMP_PATH` environment variable, which only ever offered partial support for adjusting the temporary files' location. This is because setting a `TEMP_PATH` _environment variable_ would affect [Injector](/developer_guides/extending/injector) service definitions, but would **not** affect code that referenced the `TEMP_PATH` _PHP constant_. The confusion with both environment variables and PHP constants having the same name is why the environment variable has been renamed and prefixed with `SS_`, in-keeping with other environment variables.
```
Comment (emteknetnz) [inline docs/en/04_Changelogs/4.10.0.md:17]:
```suggestion
The new `SS_TEMP_PATH` environment variable replaces the similarly-named `TEMP_PATH` _environment variable_, which only ever offered partial support for adjusting the temporary files' location. This is because setting a `TEMP_PATH` _environment variable_ would affect [Injector](/developer_guides/extending/injector) service definitions, but would **not** affect code that referenced the `TEMP_PATH` _PHP constant_. The confusion with both environment variables and PHP constants having the same name is why the _environment variable_ has been renamed and prefixed with `SS_`, in-keeping with other environment variables.
```

File: docs/en/04_Changelogs/4.10.0.md [hunk 9]
```diff
@@ -6,6 +6,18 @@
...
+
+The functionality of the `TEMP_PATH` and `TEMP_FOLDER` PHP constants remains unchanged.
```
Comment (emteknetnz) [inline docs/en/04_Changelogs/4.10.0.md:19]:
```suggestion
The functionality of the `TEMP_PATH` and `TEMP_FOLDER` _PHP constants_ remains unchanged.
```

File: src/includes/constants.php [hunk 10]
```diff
@@ -15,9 +15,9 @@
...
+ *   absolute path. No trailing slash. Can be set with the SS_TEMP_PATH environment variable.
+ * - TEMP_FOLDER: DEPRECATED. Same as TEMP_PATH.
```
Comment (emteknetnz) [inline src/includes/constants.php:20]:
```suggestion
 * - TEMP_FOLDER: DEPRECATED. Alias of TEMP_PATH.
```

File: docs/en/04_Changelogs/4.10.0.md (hunk 8 above)
Comment (emteknetnz) [reply docs/en/04_Changelogs/4.10.0.md:17]: @kinglozzer Just to confirm, what happens if your site has an existing TEMP_PATH environment variable?  Will your cache directory change? Or will it remain the same? It's worth mentioning that in the changelog so people know what to expect

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Looking really good, couple of minor formatting things, and a question re existing TEMP_PATH env variables

File: docs/en/04_Changelogs/4.10.0.md (hunk 8 above)
Comment (kinglozzer) [reply docs/en/04_Changelogs/4.10.0.md]: Nothing will change for people using `TEMP_PATH` environment variable, I’ve added an extra sentence to the start of the last paragraph to clarify that

**Comment by emteknetnz** [comment]
@kinglozzer just noticed an issues with the travis shared config that was causing this build to fail, it should be fixed now, when you get a chance could you try re-pushing (retriggering the build in travis will reuse the old config, so it needs to be a push)

**Comment by emteknetnz** [comment]
Having issues with the shared-config - I'll test it [here](https://github.com/emteknetnz/silverstripe-framework/pull/2) using github actions

**Review by emteknetnz — APPROVED** [review]
