### PR TITLE
FIX Do not insert requirements more than once

### LINKED ISSUE #6779: [3.x] Requirements::includeInHTML inserts things into more than one </head> tag
For example: if I insert a third-party Javascript snippet (like an A/B tester, etc) into my page via:

```php
Requirements::customScript('//.....');
```

... and my custom script has a _string literal_ like `var whatever = "<head></head>"`, then `Requirements::includeInHTML` will inject requirements into that `</head>` as well as the closing tag that is actually part of the DOM. This theoretically would also affect code documentation examples that have a `</head>` in them (that aren't HTML escaped).

Adding a limit of 1 to the `preg_replace` calls seems safe and fixes the problem (unless you had the same thing happening in the head tag itself).

### PR DESCRIPTION
**Pull request by robbieaverill**
This change consolidates the string replacements used to insert requirements into the page content to help ensure
that they are not compounding and overwriting eachother.
    
The added test case includes where a user may have a Javascript snippet that contains a closing head tag, and the
test ensures that it does not get injected with requirements as well as the actual head tag in the DOM.

Resolves #6779

### CODE REVIEW

**Comment by sminnee** [comment]
Have discussed an improvement to this with Robbie where we pass all the search/replace patterns into a single preg_replace call; this should give a robust & mergable approach.

It's a bugfix so good for a `3.5` merge IMO

**Comment by robbieaverill** [comment]
@sminnee updated and rebased onto `3.5`

File: view/Requirements.php [hunk 1]
```diff
@@ -892,24 +891,37 @@ public function includeInHTML($templateFile, $content) {
...
+				$replacements["/(<\/head>)/i"] = $requirements . "\\1";
 			} else {
-				$content = preg_replace("/(<\/head>)/i", $requirements . "\\1", $content);
-				$content = preg_replace("/(<\/head>)/i", $jsRequirements . "\\1", $content);
+				// Put CSS and Javascript together before the closing head tag
+				$replacements["/(<\/head>)/i"] = $requirements . $jsRequirements. "\\1";
 			}
+
+			// Replace everything at once (only once)
+			$content = preg_replace(array_keys($replacements), array_values($replacements), $content, 1);
```
Comment (sminnee) [inline view/Requirements.php]: Maybe add `if($replacements)` here? If `$canWriteToBody and $this->write_js_to_body` are both set I think that replacements will be empty?

Comment (robbieaverill) [inline view/Requirements.php]: There will always be something in the array since each condition adds to it, but it doesn't hurt to have it there anyway right? Pushing now.
