### PR TITLE
FIX: DataObject::db() doesn't respect overloaded db types (fixes #3620)

### LINKED ISSUE #3620: Overridden DB fields inherit incorrect casting
I haven’t had time to fully investigate this, but what I’m doing is overriding 'Content' in a subclass of Page:

``` php
class MyPage extends Page {
    private static $db = array(
        'Content' => 'Text'
    );
}
```

When rendered in the template, the value is treated as HTMLText (so no nl2br for me :cry:). Tried `private static $casting` to no avail, looks like it may be being cached [here](https://github.com/silverstripe/silverstripe-framework/blob/3.1/model/DataObject.php#L1680) by a previous call to `SiteTree->$field`.

### PR DESCRIPTION
**Pull request by lozcalver**

### CODE REVIEW

File: tests/model/DataObjectTest.php [hunk 1]
```diff
@@ -16,18 +16,31 @@ class DataObjectTest extends SapphireTest {
...
+
+		// Assert the base fields are excluded
 		$this->assertArrayNotHasKey('Created', $dbFields);
 		$this->assertArrayNotHasKey('LastEdited', $dbFields);
 		$this->assertArrayNotHasKey('ClassName', $dbFields);
 		$this->assertArrayNotHasKey('ID', $dbFields);
+
+		// Assert that the correct field type is returned when passing a field
+		$this->assertEquals('Varchar', $obj->db('Name'));
+		$this->assertEquals('Text', $obj->db('Comment'));
```
Comment (tractorcow) [inline tests/model/DataObjectTest.php]: You'll also need to check that the 'Comment' key is the array returned by `$obj->db()` has the right type.

Comment (tractorcow) [inline tests/model/DataObjectTest.php]: Also check that the order of db isn't changed too much from 3.1.8 :)
