### PR TITLE
FIX SSViewer::add_themes() to properly prepend

### LINKED ISSUE #7369: SSViewer::add_themes() appends theme to list rather than prepends
Replication code:

```php
public function testThemesHelpers()
    {
        SSViewer::config()->remove('themes');
        SSViewer::set_themes(['mytheme', '$default']);
        $this->assertEquals(['mytheme', '$default'], SSViewer::get_themes());

        SSViewer::add_themes(['my_more_important_theme']);
        $this->assertEquals(['my_more_important_theme', 'mytheme', '$default'], SSViewer::get_themes());
    }
```
Second assertion returns:
```php
[
    0 => 'mytheme'
    1 => '$default'
    2 => 'my_more_important_theme'
]
```
Detailed in the [RFC](https://github.com/silverstripe/silverstripe-framework/issues/5604) is that:

> `SSViewer::add_themes()` to prepend additional themes onto the current stack. If add_themes() is passed a theme already in the cascade, then the given theme is pulled to a higher precedence place in the list.

Currently the new theme is appended instead. This means that adding a theme doesn't automatically apply it, which is the expected behaviour.

### PR DESCRIPTION
**Pull request by andrewandante**
Fixes #7369

### CODE REVIEW

File: src/View/SSViewer.php [hunk 1]
```diff
@@ -165,7 +165,10 @@ public static function set_themes($themes = [])
 
     public static function add_themes($themes = [])
     {
-        SSViewer::config()->merge('themes', $themes);
+        $currentThemes = SSViewer::get_themes();
+        $finalThemes = array_merge($themes, $currentThemes);
+        SSViewer::config()->remove('themes');
```
Comment (flamerohr) [inline src/View/SSViewer.php]: `->remove()` is redundant, since `->set_themes()` uses `->set()` inside anyway.

Totally valid if it was using `->merge()` inside.

Comment (andrewandante) [reply src/View/SSViewer.php]: Thanks, have updated both this and the test 👍

**Comment by andrewandante** [comment]
Removed a stray newline 😁

File: src/View/SSViewer.php [hunk 2]
```diff
@@ -165,7 +165,9 @@ public static function set_themes($themes = [])
 
     public static function add_themes($themes = [])
     {
-        SSViewer::config()->merge('themes', $themes);
+        $currentThemes = SSViewer::get_themes();
+        $finalThemes = array_merge($themes, $currentThemes);
+        SSViewer::set_themes(array_values(array_unique($finalThemes)));
```
Comment (dhensby) [inline src/View/SSViewer.php]: I'd probably add a comment about why we're using `array_values` in case it's not clear to those who come along later

Comment (andrewandante) [reply src/View/SSViewer.php]: Comment added

**Comment by dhensby** [comment]
OK - I'm happy, but I'll leave merging so others have a chance to review
