### PR TITLE
Fix i18nTextCollector produces corrupt output / namespaces when running under PHP8.0

### LINKED ISSUE #10227: i18nTextCollector produces corrupt output / namespaces when running under PHP8.0
## Affected Version

silverstripe/framework 4.10

## Description

#9665 has introduced PHP8 support - especially for the new PHP parser tokens (`T_NAME_FULLY_QUALIFIED ` and `T_NAME_QUALIFIED`) - but is broken when collecting text from classes which are having `use` statements and even name-spaced method calls.

## Steps to Reproduce

1. Create a simple class which calls the `_t` function, has `use` statements and makes some name-spaced method calls. e.g.

```php
<?php

namespace App\Model;

use SilverStripe\ORM\DataObject;

/**
 * Class TestModelWithTFunctionCalls
 * @package App\Model
 */
class TestModelWithTFunctionCalls extends DataObject
{
    private static $table_name = 'TestModelWithTFunctionCalls';

    public function fieldLabels($includeRelations = true)
    {
        $labels = parent::fieldLabels(true);

        $currentLocale = \SilverStripe\i18n\i18n::get_locale();

        $labels['Test'] = _t(__CLASS__ . '.TEST', 'Test');

        try {

        } catch (\Exception $e) {

        }

        return $labels;
    }
}
```

2. Run the i18nTextCollector task.

As the class resists within the app directory:

```shell
vendor/bin/sake dev/tasks/i18nTextCollectorTask module=app locale=de
```

3. View the generated language file (`app/lang/de.yml`)

### Actual result

Mind the generated namespace (`App\Model\SilverStripe\ORM\DataObject\TestModelWithTFunctionCalls\\SilverStripe\i18n\i18n\get_locale`)

```yml
de:
  App\Model\SilverStripe\ORM\DataObject\TestModelWithTFunctionCalls\\SilverStripe\i18n\i18n\get_locale:
    TEST: Test
  App\Model\TestModelWithTFunctionCalls:
    PLURALNAME: 'Test Model With T Function Callss'
    PLURALS:
      one: 'A Test Model With T Function Calls'
      other: '{count} Test Model With T Function Callss'
    SINGULARNAME: 'Test Model With T Function Calls'
```

### Expected result

```yml
de:
  App\Model\TestModelWithTFunctionCalls:
    PLURALNAME: 'Test Model With T Function Callss'
    PLURALS:
      one: 'A Test Model With T Function Calls'
      other: '{count} Test Model With T Function Callss'
    SINGULARNAME: 'Test Model With T Function Calls'
    TEST: Test
```

### PR DESCRIPTION
**Pull request by bimthebam**
This PR fixes the buggy behaviour of the i18nTextCollector (#10227 ) when running under PHP8.0

### CODE REVIEW

**Comment by michalkleiner** [comment]
Thanks for the contribution @bimthebam.
Since the tests are passing now and were passing before, do you think you can have a look into the tests and update any of the tests (or provide a new one) specifically targetting the PHP8 behaviour that was broken before your PR?

File: tests/php/i18n/i18nTextCollectorTest.php [hunk 1]
```diff
@@ -300,9 +300,14 @@ public function testCollectFromCodeNamespace()
...
 
+use SilverStripe\ORM\DataObject;
+
 class MyClass extends Base implements SomeService {
     public function getNewLines(\$class) {
-        if (!is_subclass_of(\$class, DataObject::class) || !Object::has_extension(\$class, Versioned::class)) {
+        if (
+            !is_subclass_of(\$class, DataObject::class)
+            || !Object::has_extension(\$class, \SilverStripe\Versioned\Versioned::class)
+        ) {
```
Comment (michalkleiner) [inline tests/php/i18n/i18nTextCollectorTest.php:310]: Is it important for the test to have one namespace used via the use statement and one without it for the test to fail? If both were done the same way, would the test still work as expected, @bimthebam?

Comment (bimthebam) [reply tests/php/i18n/i18nTextCollectorTest.php:310]: It is, because both of them will affect the generated namespace for the language file. Have a look at my issue #10227 please. The use statement (`T_NAME_QUALIFIED`) and the direct usage of `\SilverStripe\i18n\i18n::get_locale();` (`T_NAME_FULLY_QUALIFIED`) ensure that the generated namespace is corrupted.

**Review by michalkleiner — APPROVED** [review]
Even though I didn't run this locally I'm ok with this change since it doesn't break the existing tests and the change to the test (referencing the Versioned class by its FQDN) should not change the logic of it

**Review by GuySartorelli — APPROVED** [review]
Looks good. Have tested locally and not encountered any issues.
