### PR TITLE
FIX: PDOConnector ssl_cipher bug fixes #7258

### LINKED ISSUE #7258: BUG: Build/install via cli-script fails with PDOConnector
Will be pushing a PR for this in a bit

### PR DESCRIPTION
**Pull request by johndalangin**
Fixes `ssl_cipher is undefined error` when installing Silverstripe via CLI using MySQL PDOConnector

### CODE REVIEW

File: model/connect/PDOConnector.php [hunk 1]
```diff
@@ -181,7 +181,7 @@ public function connect($parameters, $selectDB = false) {
 				}
 
 				// use default cipher if not provided
-				$options[PDO::MYSQL_ATTR_SSL_CIPHER] = $parameters['ssl_cipher'] ?: Config::inst()->get('PDOConnector', 'ssl_cipher_default');
+				$options[PDO::MYSQL_ATTR_SSL_CIPHER] = array_key_exists($parameters['ssl_cipher']) ? $parameters['ssl_cipher'] : Config::inst()->get('PDOConnector', 'ssl_cipher_default');
```
Comment (tractorcow) [inline model/connect/PDOConnector.php]: Please use isset(). array_key_exists takes two parameters.

**Comment by johndalangin** [comment]
@dhensby @tractorcow Bug Fix for #7258

File: model/connect/PDOConnector.php (hunk 1 above)
Comment (johndalangin) [inline model/connect/PDOConnector.php]: Sorry about that, will revise now.

**Comment by johndalangin** [comment]
@tractorcow Fixed. Retained the use of `array_key_exists` to be consistent with nearby lines' syntax. Let me know if you have edits.

**Comment by tractorcow** [comment]
Can be merged on green.

**Comment by johndalangin** [comment]
@tractorcow Alright, thanks! Can you kindly take a look at #7254 when you have time? Thank you.
