### PR TITLE
API Filtering on invalid relation is no longer a silent error

### LINKED ISSUE #5331: BUG: wrong Title field in SQL when adding joins
Compare:

```php
$results = $results
  ->leftJoin('BlogPost_Categories', '"BlogPost_Categories"."BlogPostID" = "SiteTree"."ID"')
  ->leftJoin('BlogCategory', '"BlogPost_Categories"."BlogCategoryID" = "BlogCategory"."ID"')
  ->filter(array("BlogCategory.Title" => $topicTitles));
			
```

with 

```php
$results = $results
  ->leftJoin('BlogPost_Categories', '"BlogPost_Categories"."BlogPostID" = "SiteTree"."ID"')
  ->leftJoin('BlogCategory', '"BlogPost_Categories"."BlogCategoryID" = "BlogCategory"."ID"')
  ->where('BlogCategory.Title = IN(\''.implode('\', \'', $topicTitles).'\'' );		
```

The former produces the following SQL: 
```sql 
SELECT [....]

FROM "SiteTree" LEFT JOIN "Page" ON "Page"."ID" = "SiteTree"."ID" LEFT JOIN "BlogPost" ON "BlogPost"."ID" = "SiteTree"."ID" LEFT JOIN "BlogPost_Categories" ON "BlogPost_Categories"."BlogPostID" = "SiteTree"."ID" LEFT JOIN "BlogCategory" AS "categories" ON "BlogPost_Categories"."BlogCategoryID" = "BlogCategory"."ID"

WHERE ("SiteTree"."Title" IN (?))
  AND ("SiteTree"."ClassName" IN (?))

ORDER BY "_SortColumn0" DESC, "PublishDate" DESC
```

As you can see this is incorrect as the wrong Title Field is filtered for... 

The latter works fine. 

I am using 3.3.1

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #5331

CC @sunnysideup  for review please. :D

It has to go into master since introducing new errors would break backwards compatibility.

### CODE REVIEW

File: model/DataList.php [hunk 1]
```diff
@@ -503,7 +503,7 @@ function(DataQuery $query, DataList $list) use ($field, &$columnName, $linearOnl
 				$fieldName = array_pop($relations);
 
 				// Apply
-				$relationModelName = $query->applyRelation($field, $linearOnly);
+				$relationModelName = $query->applyRelation($relations, $linearOnly);
```
Comment (tractorcow) [inline model/DataList.php]: This previously added the $field to the relation, but relied on it always forgiving the extra field and ignoring it.

**Comment by kinglozzer** [comment]
Looks good, merging
