### PR TITLE
FIX Files without extensions (folders) do not have a trailing period added

### LINKED ISSUE #7265: BUG: weird dot at the end of Folder Name
I tried to add a bunch of `test` folders to the Silverstripe demo site and they got a "dot" added to the end of their name: 

image

### PR DESCRIPTION
**Pull request by robbieaverill**
Fixes #7265

The issue is that `Folder::setName` calls `File::setName`, which assumes there will always be an extension and so returns `original-2.` in the format of `[original]-[unique].[extension]`, which is invalid for folders, and files without an extension in principle.

### CODE REVIEW

File: tests/filesystem/FileTest.php [hunk 1]
```diff
@@ -187,6 +187,30 @@ public function testSetNameWithInvalidExtensionDoesntChangeFilesystem() {
...
+		$duplicate->setName($name);
+		$duplicate->write();
+
+		$this->assertSame($expected, $duplicate->Name);
+	}
+
+	/**
+	 * @return array[]
+	 */
+	public function setNameFileProvider()
```
Comment (dhensby) [inline tests/filesystem/FileTest.php]: non-test methods should be `protected` or `private`

Comment (robbieaverill) [reply tests/filesystem/FileTest.php]: It's a provider - they need to be public don't they?

**Comment by robbieaverill** [comment]
It's probably affecting 3.5 as well - want me to switch and rebase?

File: tests/filesystem/FileTest.php (hunk 1 above)
Comment (dhensby) [reply tests/filesystem/FileTest.php]: I don't believe so.

**Comment by dhensby** [comment]
> It's probably affecting 3.5 as well - want me to switch and rebase?

yes please

File: tests/filesystem/FileTest.php (hunk 1 above)
Comment (robbieaverill) [reply tests/filesystem/FileTest.php]: [They do](https://phpunit.de/manual/5.7/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers) in PHPUnit 5.x at least, may have changed in 6.x

**Comment by robbieaverill** [comment]
@dhensby done, thanks :)

**Comment by tractorcow** [comment]
Test failures are due to behat / precise.
