### PR TITLE
FIX Revert natural sort

### LINKED ISSUE #6124: BUG Arraylist numeric sorting
I think [this commit](https://github.com/silverstripe/silverstripe-framework/commit/4998b8044530a83c617194d544b76a98f742386e) might have broken numeric sorting for negative numbers. It hasn't reached a release yet so would be good to get a fix in before it does (assuming it is the cause).

```php
$list = ArrayList::create(array(
	array('Sort' => 0),
	array('Sort' => -1),
	array('Sort' => 1),
	array('Sort' => -2),
	array('Sort' => 2),
	array('Sort' => -10),
	array('Sort' => 10)
));
print_r($list->sort('Sort', 'DESC')->toArray()); 
```

Before:
```php
Array
(
    [0] => Array
        (
            [Sort] => 10
        )

    [1] => Array
        (
            [Sort] => 2
        )

    [2] => Array
        (
            [Sort] => 1
        )

    [3] => Array
        (
            [Sort] => 0
        )

    [4] => Array
        (
            [Sort] => -1
        )

    [5] => Array
        (
            [Sort] => -2
        )

    [6] => Array
        (
            [Sort] => -10
        )

)
```

After:
```php
Array
(
    [0] => Array
        (
            [Sort] => 10
        )

    [1] => Array
        (
            [Sort] => 2
        )

    [2] => Array
        (
            [Sort] => 1
        )

    [3] => Array
        (
            [Sort] => 0
        )

    [4] => Array
        (
            [Sort] => -10
        )

    [5] => Array
        (
            [Sort] => -2
        )

    [6] => Array
        (
            [Sort] => -1
        )

)
```

### PR DESCRIPTION
**Pull request by jonom**
More backwards compatible and more consistent with ORM sorting (fixes #6124)

### CODE REVIEW

File: tests/model/ArrayListTest.php [hunk 1]
```diff
@@ -314,67 +314,46 @@ public function testSortSimpleDefaultIsSortedASC() {
...
-		//natural sort is only available in 5.4+
-		if (version_compare(phpversion(), '5.4.0', '<')) {
-			$this->markTestSkipped();
-		}
-		$list = new ArrayList(array(
-		array('Name' => 'Steve'),
+	public function testMixedCaseSort() {
+		// Note: Natural sorting is not expected, so if 'bonny10' were included
+		// below we would expect it to appear between bonny1 and bonny2. That's
+		// undesirable though so we're not enforcing it in tests.
```
Comment (jonom) [inline tests/model/ArrayListTest.php]: @dhensby thought I would document our thinking here for future code diggers - okay?

Comment (dhensby) [inline tests/model/ArrayListTest.php]: sure

**Comment by jonom** [comment]
Cheers Dan
