### PR TITLE
FIX: Recursion errors when sorting objects with circular dependencies (fixes #4464)

### LINKED ISSUE #4464: "Nesting level too deep" while sorting
I recently came across this bug on one of my modules: the script crashed with the message

    Fatal error: Nesting level too deep - recursive dependency? in .../framework/model/ArrayList.php on line 449

After a lot of testing I have been able to replicate the bug with the following snippet:

```
    public function testSortWithDuplicates() {
        $items = ArrayList::create();

        $items->add(DataObject::create(array('Order' => 1)));
        $items->add(DataObject::create(array('Order' => 1)));

        // Without this cycle sort does not fail
        foreach ($items as $item) {
            $item->customise(array());
        }

        // This call fails
        $items->sort('Order');
    }
```

I did not see anything inherently wrong above.

Tested on 3.1.13 and 3.2.0-beta1 on a server with PHP 5.6.11. Reported from a server with PHP 5.4.20.

### PR DESCRIPTION
**Pull request by kinglozzer**
Another attempt at #4544.

This doesn’t use `spl_object_hash()` as it can mess with the sort order itself. If all the values being sorted on are the same, then it will sort by the hashes which can result in objects coming back in a different order each time you attempt the sort.

This is simpler - we just store an array (1, 2, 3 etc) that’s passed as the penultimate argument to `array_multisort()`. This way if the sort values are the same, then the items come back in the same order that they were passed in.

### CODE REVIEW

File: tests/model/ArrayListTest.php [hunk 1]
```diff
@@ -424,6 +424,31 @@ public function testMultiSort() {
 		$this->assertEquals($list->first()->ID, 1, 'Aron.2 should be first in the list');
 		$this->assertEquals($list->last()->ID, 3, 'Bert.3 should be last in the list');
 	}
+
+	/**
+	 * Check that we don't cause recursion errors with array_multisort() and circular dependencies
+	 */
+	public function testSortWithCircularDependencies() {
+		$items = ArrayList::create();
```
Comment (willmorgan) [inline tests/model/ArrayListTest.php]: Do we want to be using Injector here, to create the ArrayList, or do we really want a real `ArrayList`?

File: model/ArrayList.php [hunk 2]
```diff
@@ -422,10 +422,15 @@ public function sort() {
 			throw new InvalidArgumentException("Bad arguments passed to sort()");
 		}
 
+		// Store the original positions of the items as a fallback, so we can preserve the original order in the event
+		// that array_multisort is unable to work out a sort order for them. This also prevents array_multisort trying
+		// to inspect object properties which can result in errors with circular dependencies
+		$originalPositions = (count($this->items)) ? range(1, count($this->items)) : array();
```
Comment (dhensby) [inline model/ArrayList.php]: please don't `count` repeatedly.

`$originalPositions = !empty($this->items) ? range(1, count($this->items)) : array();`

Comment (dhensby) [inline model/ArrayList.php]: would `array_keys()` not work just as well for this (assuming it's not an associative array)?

File: tests/model/ArrayListTest.php (hunk 1 above)
Comment (dhensby) [inline tests/model/ArrayListTest.php]: ah, yes, I tend to favour the `new xxx()` syntax in tests too.

**Comment by kinglozzer** [comment]
@willmorgan @dhensby Thanks for the feedback, fixed up those points :)
