### PR TITLE
FIX re-label forgot password for uniq id

### LINKED ISSUE #11567: Lost Password form doesn't account for non-email unique_identifier_field
### Module version(s) affected

5, 6

### Description

`unique_identifier_field` allows us to use something other than email address to uniquely identify users.

The logic in `LostPasswordHandler` makes sure that the form submission is handled correctly, but there are two other aspects that need addressing:

a) the labelling is incorrect (`SilverStripe\Security\Member.EMAIL` updates a few too many places)
b) the field type is incorrect (assumes `EmailField`)

While these are possible to overwrite, it seems heavy-handed for something that should come "bundled" with the config change.

Relates to this old issue (and related ones): https://github.com/silverstripe/silverstripe-framework/issues/9517

### How to reproduce

- add a `MemberExtension` to add a `Username` field
- set the value of `unique_identifier_field` to 'Username'
- see that the LostPassword form asks you to enter your email, instead of your username 

### Possible Solution

PR here: https://github.com/silverstripe/silverstripe-framework/pull/11568

### Validations

- [x] Check that there isn't already an issue that reports the same bug
- [x] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11568

### PR DESCRIPTION
**Pull request by andrewandante**
## Description

 Defaults for non-Email unique identifier fields, including a TextField in the form and a sensible label.

## Manual testing steps

Set `unique_identifier_field` to something non-email.
See that it changes the field label.

## Issues

Fixes #11567 

## Pull request checklist
- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [x] CI is green

### CODE REVIEW

File: src/Security/MemberAuthenticator/LostPasswordForm.php [hunk 1]
```diff
@@ -23,8 +25,15 @@ class LostPasswordForm extends MemberLoginForm
...
+        if ($uniqueIdentifier === 'Email') {
+            $emailField = EmailField::create('Email', _t('SilverStripe\\Security\\Member.EMAIL', 'Email'));
+        } else {
+            // This field needs to still be called Email, but we can re-label it
+            $emailField = TextField::create('Email', _t('SilverStripe\\Security\\Member.LOSTPASSWORDLABEL', $uniqueIdentifier));
+        }
         return FieldList::create(
-            EmailField::create('Email', _t('SilverStripe\\Security\\Member.EMAIL', 'Email'))
+            $emailField
         );
```
Comment (GuySartorelli) [inline src/Security/MemberAuthenticator/LostPasswordForm.php]: May as well consolidate this into a single line now
```suggestion
        return FieldList::create($emailField);
```

File: src/Security/MemberAuthenticator/LostPasswordForm.php [hunk 2]
```diff
@@ -23,8 +25,15 @@ class LostPasswordForm extends MemberLoginForm
      */
     public function getFormFields()
     {
+        $uniqueIdentifier = Member::config()->get('unique_identifier_field');
+        if ($uniqueIdentifier === 'Email') {
+            $emailField = EmailField::create('Email', _t('SilverStripe\\Security\\Member.EMAIL', 'Email'));
+        } else {
+            // This field needs to still be called Email, but we can re-label it
+            $emailField = TextField::create('Email', _t('SilverStripe\\Security\\Member.LOSTPASSWORDLABEL', $uniqueIdentifier));
+        }
```
Comment (GuySartorelli) [inline src/Security/MemberAuthenticator/LostPasswordForm.php]: Might be worth getting a member singleton and calling `$singleton->fieldLabel($uniqueIdentifier)` to get the field label. Then we don't need any branching logic at all.

**Review by GuySartorelli — CHANGES_REQUESTED** [review]

File: src/Security/MemberAuthenticator/LostPasswordForm.php (hunk 2 above)
Comment (andrewandante) [reply src/Security/MemberAuthenticator/LostPasswordForm.php]: That's a good trick! Still need to split on fieldtype though I think, the email validation on the email field still seems valuable.

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
LGTM - just noticed the branch this is targetting. No sense in this waiting until June - can you please retarget to `5.3` so it can be released as a patch?

Would be really good if you can include a unit test as well, if you have time.

**Comment by andrewandante** [comment]
Alrighty @GuySartorelli I think I'm done messing about 😄

**Review by GuySartorelli — APPROVED** [review]
LGTM, thanks for this
