### PR TITLE
FIX don't count records twice on a GridField if there is a GridFieldPaginator

### LINKED ISSUE #11592: GridField paginator count() leads to duplicated query
### Module version(s) affected

5.x

### Description

So this is the last duplicated query on a regular model admin page :-D after my other fixes

Again, not a big deal as such, but so very annoying anyway (for me, at least...)

The issue arise from the GridFieldPaginator calling $list->count() and the FieldHolder calling count($list). Both calls trigger a count query on the list.

Image

### How to reproduce

Have a GridField with a paginator component
See the duplicated query

### Possible Solution

For GridField with a Paginator, rely on the already queried data instead of making a fresh query

### Additional Context

_No response_

### Validations

- [x] Check that there isn't already an issue that reports the same bug
- [x] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

### PR DESCRIPTION
**Pull request by lekoala**
## Description
Fixes https://github.com/silverstripe/silverstripe-framework/issues/11592, see issue for context

## Manual testing steps
Check that no duplicate queries are being made to count records

## Issues
https://github.com/silverstripe/silverstripe-framework/issues/11592

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [x] CI is green

### CODE REVIEW

File: src/Forms/GridField/GridField.php [hunk 1]
```diff
@@ -548,6 +549,12 @@ public function FieldHolder($properties = [])
                     }
                 }
             }
+            if ($item instanceof GridFieldPaginator) {
+                $parameters = $item->getTemplateParameters($this);
+                if ($parameters) {
+                    $total = $parameters->NumRecords;
+                }
+            }
```
Comment (GuySartorelli) [inline src/Forms/GridField/GridField.php]: I'm not convinced it's worth running all of the logic in `getTemplateParameters()` just for this - I'd be more comfortable with a `getTotalItems()` method being added to `GridFieldPaginator` in a minor release, which can then be called here.

I will note the beta release for CMS 5.4 (which is also the feature freeze for all of CMS 5) is currently scheduled for 17 Feb, so if you want to make that change, it has to be merged by then.

Comment (lekoala) [reply src/Forms/GridField/GridField.php]: yes, i fully agree. i was a bit unsure about adding a new method but i'm happy to add it and adjust to PR

**Review by GuySartorelli — APPROVED** [review]
LGTM, thanks for making that change.

I'll retarget this to `5` to be included in the 5.4 minor release as per https://github.com/silverstripe/silverstripe-framework/pull/11593#discussion_r1940041634
