### PR TITLE
FIX: DataQuery::applyRelation using incorrect foreign key (fixes #3954)

### LINKED ISSUE #3954: DataQuery applyRelation has_one join incorrect foreignKey
$has_one = array_flip($model->has_one());

I getting incorrect foreignKey while I have multiple has_one with same class.

e.g.

$has_one = array(
    'Owner' => 'Member',
    'Father' => 'Member',
    'Son' => 'Member'
);

It always getting the "Son" as foreignKey.

### PR DESCRIPTION
**Pull request by kinglozzer**
In the case of `has_one`, the foreign key is always the relation name!

### CODE REVIEW

File: tests/model/DataQueryTest.php [hunk 1]
```diff
@@ -241,7 +254,7 @@ class DataQueryTest_A extends DataObject implements TestOnly {
 	);
 
 	private static $has_one = array(
-		'TestC' => 'DataQueryTest_C',
+		'TestC' => 'DataQueryTest_C'
```
Comment (kinglozzer) [inline tests/model/DataQueryTest.php]: CONVENTIONS! Will fix :)

Comment (dhensby) [inline tests/model/DataQueryTest.php]: Trailing commas FTW!

**Comment by dhensby** [comment]
Looks like a good fix!
