### PR TITLE
BUG Correct behaviour of publish with $createNewVersion = true

### LINKED ISSUE #5040: Reverting a page to a specific version is not working correctly : SS 3.2
When we use 'Revert to this version' in History tab of a cms page, it creates a new version record for child Page_versions table but not in SiteTree_versions (Page extends SiteTree and when Page has db array). 

Then we can't do anymore reverts as we have orphaned record in Page_versions table. This happens only in SS 3.2 version but not in SS 3.1

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #5040
Cleanup code to make behaviour more apparent.

Main points in this fix:
- Instead of guessing next version, set Version = null prior to write to force new version on write.
- During write, get version from base table instead of the current table (as only the base table has a Version field).

Optional optimisation:
- In 4.0 we should probably pass back nextVersion from augmentWriteVersioned to prevent the DB::query having to be executed for multiple tables.

### CODE REVIEW

**Comment by tractorcow** [comment]
@priyashantha  please test and confirm this fixes your issue.

File: model/Versioned.php [hunk 1]
```diff
@@ -805,56 +817,64 @@ public function latestPublished() {
...
 		if(is_numeric($fromStage)) {
 			$from = Versioned::get_version($baseClass, $this->owner->ID, $fromStage);
 		} else {
 			$this->owner->flushCache();
-			$from = Versioned::get_one_by_stage($baseClass, $fromStage, "\"{$baseClass}\".\"ID\"={$this->owner->ID}");
+			$from = Versioned::get_one_by_stage($baseClass, $fromStage, array(
+				"\"{$baseClass}\".\"ID\" = ?" => $this->owner->ID
+			));
+		}
+		if(!$from) {
```
Comment (tractorcow) [inline model/Versioned.php]: This early return (instead of a huge if() body) makes this change look larger than it really is. Maybe view side-by-side?

**Comment by priyashantha** [comment]
@tractorcow Thank you very much for the update and I'll have test with the issue and let you know :)

**Comment by tractorcow** [comment]
Yikes, it looks like there are some DB schema specific failures here.

**Comment by tractorcow** [comment]
I forgot that some connectors like returning string values for numeric values... changed `===` to `==` for test.

File: model/Versioned.php (hunk 1 above)
Comment (dhensby) [inline model/Versioned.php]: appending `?w=1` to the diff URL will hide indentation changes

**Comment by dhensby** [comment]
thanks :tractor: :cow:

**Comment by tractorcow** [comment]
Yay.

**Comment by priyashantha** [comment]
@tractorcow This is great and working fine. Is there any new tag including this fix to refer us in composer.json?

**Comment by tractorcow** [comment]
Not yet, I'm investigating a possible regression in this fix. We will need to double check it's compatibility with other modules before we tag it.

See https://github.com/silverstripe-labs/silverstripe-fulltextsearch/pull/109 which was broken at this fix.
