### PR TITLE
BUG Ensure that installer can create an initial admin account

### LINKED ISSUE #7124: error installing 4.0.0-beta1
I have installed 4.0.0-beta1 via composer create-project silverstripe/installer ./ 4.0.0-beta1

When I try and install SilverStripe using install.php I am receiving the following error after entering database details and admin credentials

```
Building database schema...
POST /54.5/constant-sd/www/install.php

Line 233 in G:\sites\54.5\constant-sd\www\framework\src\Dev\Install\Installer.php

Source

224             $dbAdmin = new DatabaseAdmin();
225             $dbAdmin->setRequest($request);
226             $dbAdmin->pushCurrent();
227             $dbAdmin->doInit();
228             $dbAdmin->doBuild(true);
229 
230             // Create default administrator user and group in database
231             // (not using Security::setDefaultAdmin())
232             $adminMember = DefaultAdminService::singleton()->findOrCreateDefaultAdmin();
233             $adminMember->Email = $config['admin']['username'];
234             $adminMember->Password = $config['admin']['password'];
235             $adminMember->PasswordEncryption = Security::config()->get('encryption_algorithm');
236 
237             try {
238                 $this->statusMessage('Creating default CMS admin account...');
239                 $adminMember->write();
Trace

Monolog\ErrorHandler->handleError(2,Creating default object from empty value,G:\sites\54.5\constant-sd\www\framework\src\Dev\Install\Installer.php,233,Array) 
Installer.php:233
SilverStripe\Dev\Install\Installer->SilverStripe\Dev\Install\{closure}(SilverStripe\Control\HTTPRequest) 
call_user_func(Closure,SilverStripe\Control\HTTPRequest) 
HTTPApplication.php:66
SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) 
HTTPMiddlewareAware.php:65
SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest,Closure) 
HTTPApplication.php:67
SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest,Closure,1) 
Installer.php:249
SilverStripe\Dev\Install\Installer->install(Array) 
install5.php:270
include(G:\sites\54.5\constant-sd\www\framework\src\Dev\Install\install5.php) 
install.php:27
include(...\www\framework\src\Dev\Install\install.php) 
install.php:15
Creating default CMS admin account...
[Alert] Call to undefined method stdClass::write()
POST /www/install.php

Line 239 in ...\www\framework\src\Dev\Install\Installer.php

Source

230             // Create default administrator user and group in database
231             // (not using Security::setDefaultAdmin())
232             $adminMember = DefaultAdminService::singleton()->findOrCreateDefaultAdmin();
233             $adminMember->Email = $config['admin']['username'];
234             $adminMember->Password = $config['admin']['password'];
235             $adminMember->PasswordEncryption = Security::config()->get('encryption_algorithm');
236 
237             try {
238                 $this->statusMessage('Creating default CMS admin account...');
239                 $adminMember->write();
240             } catch (Exception $e) {
241                 $this->statusMessage(
242                     sprintf('Warning: Default CMS admin account could not be created (error: %s)', $e->getMessage())
243                 );
244             }
245 
Trace
```

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #7124

### CODE REVIEW

**Comment by Firesphere** [comment]
Nice one @tractorcow !

File: src/Dev/Install/Installer.php [hunk 1]
```diff
@@ -229,9 +228,15 @@ public function index() {
...
             // (not using Security::setDefaultAdmin())
-            $adminMember = DefaultAdminService::singleton()->findOrCreateDefaultAdmin();
-            $adminMember->Email = $config['admin']['username'];
-            $adminMember->Password = $config['admin']['password'];
+            $username = $config['admin']['username'];
+            $password = $config['admin']['password'];
+            $adminMember = DefaultAdminService::singleton()
+                ->findOrCreateAdmin(
+                    $username,
+                    _t(DefaultAdminService::class . '.DefaultAdminFirstname', 'Default Admin')
```
Comment (tractorcow) [inline src/Dev/Install/Installer.php]: It just won't collect. It'll still collect from the string in defaultadminservice though.
