### PR TITLE
FIX Table aliases are retained on base tables in queries built using SQLConditionalExpression

### LINKED ISSUE #8917: Aliases on the base table using SQLSelect are lost
## Affected Version

4.x

## Description

Here's some code to illustrate the problem

```
$select = SQLSelect::create('*', ['MyTableAlias' => 'MyTable']);
$sql = $select->sql();
echo $sql; // SELECT * FROM MyTable
```

## Steps to Reproduce

You can write the above code verbatim. I've got a PR (#8918) that illustrates the problem:

```
1) SilverStripe\ORM\Tests\SQLSelectTest::testBaseTableAliases
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'SELECT * FROM "MyTable" AS "MyTableAlias"'
+'SELECT * FROM "MyTable"'
```

## Notes

This is pretty easy to track down in the code:

https://github.com/silverstripe/silverstripe-framework/blob/db610aaf3bef897a1f3b5c60a307ee72a5d2a499/src/ORM/Queries/SQLConditionalExpression.php#L313-L340

The base table is shifted off the front of all tables so the alias is lost (it's stored as the key of that array value).

### PR DESCRIPTION
**Pull request by ScopeyNZ**
Fixes #8917

### CODE REVIEW

File: src/ORM/Queries/SQLConditionalExpression.php [hunk 1]
```diff
@@ -283,6 +283,10 @@ public function getJoins(&$parameters = array())
             // array('type' => 'inner', 'table' => 'SiteTree', 'filter' => array("SiteTree.ID = 1",
             // "Status = 'approved'", 'order' => 20))
             if (!is_array($join)) {
+                if (!empty($alias) && !is_numeric($alias) && $alias !== trim($join, '"')) {
```
Comment (tractorcow) [inline src/ORM/Queries/SQLConditionalExpression.php]: Should you have trimmed $alias in this comparison too?

Comment (tractorcow) [reply src/ORM/Queries/SQLConditionalExpression.php]: This is my fault. Framework is littered with "this table is quoted" and "this table must not be quoted" everywhere.

Comment (ScopeyNZ) [reply src/ORM/Queries/SQLConditionalExpression.php]: > Should you have trimmed $alias in this comparison too?

Hmmn. I trimmed it after but it makes sense to move that above. I'll update it quickly
