### PR TITLE
BUG Fix joins on tables containing "select" being mistaken for sub-selects

### LINKED ISSUE #3965: Versioned tables with "select" in their name cause a bad SQL query to be generated
df6a8b6 / #3282 (released first in 3.1.6) introduced a bug that prevents versioned table name replacement from working for tables that have "select" in their name. Quotes are incorrectly removed from the table name string in [SQLQuery:906](https://github.com/silverstripe/silverstripe-framework/blob/3.1.10/model/SQLQuery.php#L906-L907):

```php
// breaks in the case $join['table'] = 'ProductSelectorPage'; for example
$table = strpos(strtoupper($join['table']), 'SELECT') ? $join['table'] : "\"" . $join['table'] . "\"";
```

It appears that the change in this commit/issue relies entirely on string matching, so the feature either needs to be rethought, or the substring match needs to be made more specific so that it cannot collide with a table name:

```php
$table = strpos(strtoupper($join['table']), '(SELECT') === 0 ? $join['table'] : "\"" . $join['table'] . "\"";
```

cc: @senorgeno

### PR DESCRIPTION
**Pull request by tractorcow**
Fix PHPDoc on SQLQuery::addFrom and SQLQuery::setFrom
Fixes #3965

### CODE REVIEW

File: model/SQLQuery.php [hunk 1]
```diff
@@ -903,9 +903,13 @@ public function sql() {
...
 
-				$table = strpos(strtoupper($join['table']), 'SELECT') ? $join['table'] : "\"" 
-					. $join['table'] . "\"";
-				$aliasClause = ($alias != $join['table']) ? " AS \"" . Convert::raw2sql($alias) . "\"" : "";
+				// Ensure tables are quoted, unless the table is actually a sub-select
+				$table = preg_match('/\bSELECT\b/i', $join['table'])
+					? $join['table']
+					: "\"{$join['table']}\"";
+				$aliasClause = ($alias != $join['table'])
+						? " AS \"{$alias}\""
```
Comment (tractorcow) [inline model/SQLQuery.php]: Changed because raw2sql is not the Ansi standard way to escape SQL identifiers.

http://savage.net.au/SQL/sql-99.bnf.html#delimited%20identifier

Comment (dhensby) [inline model/SQLQuery.php]: Well... if the tests pass

**Comment by dhensby** [comment]
Well... if the tests pass
