### PR TITLE
API Refactor out Page default classname hack

### LINKED ISSUE #1932: [2011-03-28] Allow custom ENUM defaults in Database->requireField() in order to support SiteTree->Page special case
created by: @chillu (ischommer)
assigned to: @sminnee (sminnee)
created at: 2011-03-28
original ticket: http://open.silverstripe.org/ticket/6563

---

Specifically, to remove the SiteTree hardcoding from Database - see  http://open.silverstripe.org/ticket/6519 

Fix this code:

```
// If enums/sets are being modified, then we need to fix existing data in the table.
			// Update any records where the enum is set to a legacy value to be set to the default.
			// One hard-coded exception is SiteTree - the default for this is Page.
			foreach(array('enum','set') as $enumtype) {
				if(preg_match("/^$enumtype/i",$specValue)) {
					$newStr = preg_replace("/(^$enumtype\s*\(')|('$\).*)/i","",$spec_orig);
					$new = preg_split("/'\s*,\s*'/", $newStr);
				
					$oldStr = preg_replace("/(^$enumtype\s*\(')|('$\).*)/i","", $fieldValue);
					$old = preg_split("/'\s*,\s*'/", $newStr);

					$holder = array();
					foreach($old as $check) {
						if(!in_array($check, $new)) {
							$holder[] = $check;
						}
					}
					if(count($holder)) {
						$default = explode('default ', $spec_orig);
						$default = $default[1];
						if($default == "'SiteTree'") $default = "'Page'";
						$query = "UPDATE \"$table\" SET $field=$default WHERE $field IN (";
						for($i=0;$i+1<count($holder);$i++) {
							$query .= "'{$holder[$i]}', ";
						}
						$query .= "'{$holder[$i]}')";
						DB::query($query);
						$amount = DB::affectedRows();
						$this->alterationMessage("Changed $amount rows to default value of field $field (Value: $default)");
					}
				}
			}
```

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #1932 

Must be merged with https://github.com/silverstripe/silverstripe-cms/pull/1370

### CODE REVIEW

File: tests/model/DBClassNameTest.php [hunk 1]
```diff
@@ -63,29 +63,41 @@ public function testBaseClassDetection() {
...
 		// Implicit table
 		$field4 = new DBClassName('MyClass');
 		$field4->setTable('DBClassNameTest_ObjectSubClass_versions');
 		$this->assertEquals('DBClassNameTest_Object', $field4->getBaseClass());
+		$this->assertEquals('DBClassNameTest_Object', $field4->getDefault());
 
 		// Missing
 		$field5 = new DBClassName('MyClass');
 		$this->assertEquals('DataObject', $field5->getBaseClass());
+		$this->assertNotEquals('DataObject', $field5->getDefault());
```
Comment (tractorcow) [inline tests/model/DBClassNameTest.php]: Note that this is "assertNotEquals" beacuse there is no dataobject with classname value "DataObject".
