### PR TITLE
FIX: Ensure HasManyList foreign ID filter includes table name (fixes #7023)

### LINKED ISSUE #7023: HasManyList::foreignIDFilter() doesn’t include table name
`HasManyList::foreignIDFilter()` does not include the table name for the component class, which can result in `Column '<column>' in where clause is ambiguous` errors when related models share the same component names. Example model setup below:

```php
class Company extends DataObject
{
    private static $has_many = [
        'Searches' => 'Search',
        'Responses' => 'Response'
    ];
}

class Search extends DataObject
{
    private static $db = [
        'Status' => 'Enum(array("Inactive", "Active"), "Inactive")'
    ];

    private static $has_one = [
        'Company' => 'Company'
    ];

    private static $has_many = [
        'Responses' => 'Response'
    ];
}

class Response extends DataObject
{
    private static $has_one = [
        'Search' => 'Search',
        'Company' => 'Company'
    ];
}

// SELECT DISTINCT count(DISTINCT "Response"."ID") AS "Count" FROM "Response" LEFT JOIN "Search" ON "Search"."ID" = "Response"."SearchID" WHERE ("CompanyID" = ?) AND ("Search"."Status" = ?)
// Query error: Column 'CompanyID' in where clause is ambiguous
echo $company->Responses()->filter([
    'Search.Status' => 'Active'
])->count();
```

Workaround for the issue is just to give the relations different names on each model

### PR DESCRIPTION
**Pull request by kinglozzer**
Fixes #7023

### CODE REVIEW

File: model/HasManyList.php [hunk 1]
```diff
@@ -45,7 +45,7 @@ protected function foreignIDFilter($id = null) {
 		if ($id === null) $id = $this->getForeignID();
 
 		// Apply relation filter
-		$key = "\"$this->foreignKey\"";
+		$key = "\"$this->dataClass\".\"$this->foreignKey\"";
```
Comment (tractorcow) [inline model/HasManyList.php]: You need to check the table the field is actually on; E.g. ParentID is on SiteTree table, not on ErrorPage table. Can you please use the ClassInfo::table_for_object_field() API?

A unit test to demonstrate this would help too please. :)

Comment (kinglozzer) [inline model/HasManyList.php]: Done and done :)

File: tests/model/HasManyListTest.php [hunk 2]
```diff
@@ -59,4 +69,61 @@ public function testRemoveRelation() {
...
+		$johnsCars = $company->CompanyCars()->filter(array('User.Name' => 'John Smith'));
+		$this->assertEquals(1, $johnsCars->count(), 'John Smith should have one company car');
+
+		$jennysCars = $company->CompanyCars()->filter(array('User.Name' => 'Jenny Smith'));
+		$this->assertEquals(2, $jennysCars->count(), 'John Smith should have two company cars');
+	}
+
+}
+
+class HasManyListTest_Company extends DataObject {
```
Comment (dhensby) [inline tests/model/HasManyListTest.php]: `implements TestOnly` please

File: tests/model/HasManyListTest.php [hunk 3]
```diff
@@ -59,4 +69,61 @@ public function testRemoveRelation() {
...
+	);
+
+	private static $has_many = array(
+		'Employees' => 'HasManyListTest_Employee',
+		'CompanyCars' => 'HasManyListTest_CompanyCar'
+	);
+
+}
+
+class HasManyListTest_Employee extends DataObject {
```
Comment (dhensby) [inline tests/model/HasManyListTest.php]: `TestOnly`

File: tests/model/HasManyListTest.php [hunk 4]
```diff
@@ -59,4 +69,61 @@ public function testRemoveRelation() {
...
+		'Company' => 'HasManyListTest_Company'
+	);
+
+	private static $has_many = array(
+		'CompanyCars' => 'HasManyListTest_CompanyCar'
+	);
+
+}
+
+class HasManyListTest_CompanyCar extends DataObject {
```
Comment (dhensby) [inline tests/model/HasManyListTest.php]: `TestOnly`

File: tests/model/HasManyListTest.php [hunk 5]
```diff
@@ -59,4 +69,61 @@ public function testRemoveRelation() {
...
 
+	/**
+	 * Test that multiple models with the same "has_one" relation name (and therefore the same "<hasone>ID"
+	 * column name) do not trigger a "Column '<hasone>ID' in where clause is ambiguous" error
+	 */
+	public function testAmbiguousRelationshipNames() {
+		$company = $this->objFromFixture('HasManyListTest_Company', 'silverstripe');
+
+		$johnsCars = $company->CompanyCars()->filter(array('User.Name' => 'John Smith'));
+		$this->assertEquals(1, $johnsCars->count(), 'John Smith should have one company car');
```
Comment (dhensby) [inline tests/model/HasManyListTest.php]: `assertCount(1, $johnsCars)` is a better assertion :)
