### PR TITLE
FIX: Ensure that types are preserved fetching from database

### LINKED ISSUE #7039: [ORM] Inconsistent DB ORM casting of int values
This covers a range of issues, but is essentially caused by the lack of consistency between the various DB connector classes in the way that they encode integer values. Some encode them as strings, others as real integer.

This issue causes increasing breakage in client scripts where we work with de-serialised client side models, but in a type-strict way. E.g. `this.props.id === checkID`, which may not have consistent behaviour when using another DB backend.

I won't propose a desired resolution, but previously discussed suggestions included:
 - Enforce strictly-typed DB connectors (e.g. PDO, move to DBAL (https://github.com/silverstripe/silverstripe-framework/issues/6632))
 - Cast int fields at the DataObject level (cast on write, store normalised values)
 - Cast values during serialisation for the front-end
 
 This will also fix:

 * #3473
 * #6709

# Related Pull Requests
* [x] https://github.com/silverstripe/silverstripe-postgresql/pull/91
* [ ] https://github.com/silverstripe/silverstripe-framework/pull/8448

### PR DESCRIPTION
**Pull request by sminnee**
This ensures that numeric fields appear in PHP as int/float values
rather than strings, which allows the development of more type-safe PHP
code.

This doesn’t work on the legacy mysql driver and this will now throw
a notice-level error. It requires mysqlnd.

Fixes #7039, and other bugs such as #6709

Also requires https://github.com/silverstripe/silverstripe-postgresql/pull/91

Taken from https://github.com/open-sausages/silverstripe-framework/commit/f4e6aae411f2ffcfd52ff08e6bf66dbe4eeee464

### CODE REVIEW

**Comment by sminnee** [comment]
OK @dhensby @tractorcow I made quite a bit of progress with this once I realised that the underlying issue is that, when using PDO, you're expected to also use their transaction methods.

Unfortunately their transaction methods don't supported nested transactions. So, the current code "fakes" the nested transactions by making any internal transaction a no-op. Right now this is breaking the tests that do things with transactions.

So, there's a questions: how badly do we need nested transactions that allow you to roll-back only the inner transaction? I would probably advocate for a nested transaction model where if an inner transaction had an issue, the top-level transaction would also be rolled back. In real world code where transaction rollback is primarily to prevent data corruption in the case of failures, this should do.

We can then amend our tests to suit this expectation.

Related: does DBAL support nested transactions?

**Comment by sminnee** [comment]
OK I've had a look at https://www.doctrine-project.org/projects/doctrine-dbal/en/2.8/reference/transactions.html#transaction-nesting about DBAL, and they do "fake" transaction nesting similar to what I have implemented here for PDODatabase. I'm going to tidy up this implementation so that it matches their semantics and then get our test suite working with that.

**Comment by tractorcow** [comment]
Ah yes, I found my own proof of concept of such an issue a while back.

https://gist.github.com/tractorcow/390c9075020b6e2fdfa807c835403afa

Maybe you can fix it. :)

**Comment by sminnee** [comment]
Yeah the big breakthrough was realising that doing transactions without the PDO's built-in transaction methods was a big idea.

I've solved the problem now — it depends on a postgresql PR to get the build passing, but the code is written.

I just need feedback on whether it's solved in the right way.

**Comment by sminnee** [comment]
OK I've gone with formally declaring booleans to be `1` and `0`, following MySQL's lead (which doesn't have a native boolean type)

**Comment by sminnee** [comment]
@robbieaverill @kinglozzer might be good to broaden the review pool for this? See also https://github.com/silverstripe/silverstripe-postgresql/pull/91

**Comment by kinglozzer** [comment]
I’ll try to find time to do a proper code review later, immediate thoughts/queries:

- I’m not familiar with the finer points of transactions and what our API currently supports, but is this acceptable for a mid-4.x-release-line change? https://github.com/silverstripe/silverstripe-framework/pull/8448/files#diff-517cba5a1e63143651649368ef337664R333
- If we are going to go with this change, do we need to either:
  - Make it opt-in? I can’t imagine why anyone would be doing strict type checks on incorrect types, but you never know...
  - Somehow preserve the existing transaction behaviour - in a “legacy transaction manager” perhaps?

My preference would be for booleans to represented as actual booleans, but probably at a higher (likely DBField) level. i.e. an `SQLSelect` might return a `0` or `1`, but `$myDataObject->BooleanField` would return an actual boolean. That can always come after this PR of course :)

File: tests/php/ORM/DatabaseTest.php [hunk 1]
```diff
@@ -270,4 +271,40 @@ public function testFieldTypes()
...
+            $success = DataObject::get(MyObject::class, "\"MyField\"='Read only success'");
+            $fail = DataObject::get(MyObject::class, "\"MyField\"='Read only page failed'");
+
+            //This page should be in the system
+            $this->assertTrue(is_object($success) && $success->exists());
+
+            //This page should NOT exist, we had 'read only' permissions
+            $this->assertFalse(is_object($fail) && $fail->exists());
+        } else {
+            $this->markTestSkipped('Current database is doesn\'t support transactions');
```
Comment (robbieaverill) [inline tests/php/ORM/DatabaseTest.php]: You could probably do an early return instead to save all the indentation

File: tests/php/ORM/DatabaseTest.php [hunk 2]
```diff
@@ -231,4 +237,74 @@ function () use (&$failed) {
...
+            DataObject::flush_and_destroy_cache();
+
+            $success = DataObject::get(MyObject::class, "\"MyField\"='Read only success'");
+            $fail = DataObject::get(MyObject::class, "\"MyField\"='Read only page failed'");
+
+            //This page should be in the system
+            $this->assertTrue(is_object($success) && $success->exists());
+
+            //This page should NOT exist, we had 'read only' permissions
+            $this->assertFalse(is_object($fail) && $fail->exists());
```
Comment (robbieaverill) [inline tests/php/ORM/DatabaseTest.php]: What do you think about
```suggestion
            $this->assertNotInternalType('object', $fail);
            $this->assertFalse($fail->exists()); 
```

Note that second assertion will probably fail because `$fail` isn't an object, so maybe omit it. We could do the opposite assertions for the `assertTrue()` line above

File: src/ORM/Connect/PDOConnector.php [hunk 3]
```diff
@@ -468,4 +496,48 @@ public function isActive()
...
+     */
+    public function transactionRollback()
+    {
+        $this->inTransaction = false;
+        return $this->pdoConnection->rollBack();
+    }
+
+    /**
+     * @inherit
+     */
```
Comment (robbieaverill) [inline src/ORM/Connect/PDOConnector.php]: You can omit these, the `@inheritDoc` tag on its own is functionally equivalent to not having a doc block at all

File: src/ORM/Connect/PDOConnector.php [hunk 4]
```diff
@@ -213,6 +231,16 @@ public function connect($parameters, $selectDB = false)
         }
     }
 
+
+    /**
+     * Return the driver for this connector
+     * E.g. 'mysql', 'sqlsrv', 'pgsql'
```
Comment (robbieaverill) [inline src/ORM/Connect/PDOConnector.php]: Can we add `@return string`?

File: src/ORM/Connect/PDOConnector.php [hunk 5]
```diff
@@ -64,6 +64,18 @@ class PDOConnector extends DBConnector
      */
     protected $cachedStatements = array();
 
+    /**
+     * Driver
+     * @var string
+     */
+    private $driver = null;
```
Comment (robbieaverill) [inline src/ORM/Connect/PDOConnector.php]: I think we should use protected over private

**Comment by sminnee** [comment]
> I’m not familiar with the finer points of transactions and what our API currently supports, but is this acceptable for a mid-4.x-release-line change? https://github.com/silverstripe/silverstripe-framework/pull/8448/files#diff-517cba5a1e63143651649368ef337664R333

The nature of this changes is that it moves away from _genuine_ support for nested transactions to simulated nested transactions, which means that child transactions can't be rolled back without rolling back the entire transaction, which is essentially the same behaviour as savepoints.

This is because PDO is dislikes running transaction-control statements as regular queries; it really wants you to use its own transaction control commands instead. Specifically, they cause bugs when running unbuffered queries, and unbuffered queries are necessary to get correct type data.

The two broad paths that I considered were:

 * Deprecate 'true' nested queries
 * Deprecate PDO

I'm not joking about the 2nd one. Although on the surface of it using a built-in abstraction library is "better", in practise, PDO has been a deeply disappointing system at many turns, providing underwhelming lowest-common-denominator functionality and confusing bugs and inconsistencies.

However, I've opted for the first solution in this PR, mainly because it matches what we would need to do in order to move to DBAL, which Dan has previously raised as an option for the future. So, PDO lives on. ;-)

> My preference would be for booleans to represented as actual booleans, but probably at a higher (likely DBField) level. i.e. an SQLSelect might return a 0 or 1, but $myDataObject->BooleanField would return an actual boolean. That can always come after this PR of course :)

Yeah, we can't easily do this as the database level because MySQL doesn't return "type = boolean" data. Creating a DataObject-level casting of values to booleans would require the instantiation of a whole lot of DBBoolean objects and I'm worried about the performance impact, so I've stayed away from that.

File: src/ORM/Connect/NestedTransactionManager.php [hunk 6]
```diff
@@ -0,0 +1,110 @@
...
+        }
+
+        if ($chain) {
+            return $this->transactionStart();
+        }
+    }
+
+    /**
+     * @inherit
+     */
```
Comment (robbieaverill) [inline src/ORM/Connect/NestedTransactionManager.php]: Remove

File: src/ORM/Connect/MySQLTransactionManager.php [hunk 7]
```diff
@@ -0,0 +1,98 @@
...
+
+        $this->dbConn->query('COMMIT');
+
+        $this->inTransaction = false;
+        return true;
+    }
+
+    /**
+     * @inherit
+     */
```
Comment (robbieaverill) [inline src/ORM/Connect/MySQLTransactionManager.php]: Remove

File: src/ORM/Connect/MySQLDatabase.php [hunk 8]
```diff
@@ -298,80 +299,77 @@ public function searchEngine(
...
-            return false;
-        }
-        --$this->transactionNesting;
-        if ($this->transactionNesting <= 0) {
-            $this->transactionNesting = 0;
-            $this->query('COMMIT AND ' . ($chain ? '' : 'NO ') . 'CHAIN');
+        $result = $this->getTransactionManager()->transactionEnd();
+
+        if ($chain) {
+            Deprecation::notice('4.3', '$chain argument is dereprecated');
```
Comment (robbieaverill) [inline src/ORM/Connect/MySQLDatabase.php]: Type in deprecated

File: src/ORM/Connect/MySQLDatabase.php [hunk 9]
```diff
@@ -298,80 +299,77 @@ public function searchEngine(
...
+        user_error('transactionSavepoint() no longer does anything', E_USER_WARNING);
     }
 
     public function transactionRollback($savepoint = false)
     {
-        // Named transaction
         if ($savepoint) {
-            $this->query('ROLLBACK TO ' . $savepoint);
-            return true;
+            user_error('transactionRollback() $savepont option no longer does anything', E_USER_WARNING);
```
Comment (robbieaverill) [inline src/ORM/Connect/MySQLDatabase.php]: Type in variable name

File: src/ORM/Connect/MySQLDatabase.php [hunk 10]
```diff
@@ -49,6 +49,12 @@ class MySQLDatabase extends Database
      */
     private static $charset = 'utf8';
 
+    /**
+     * Cache for getTransactionManager()
+     * @var TransactionManager
+     */
+    private $transactionManager = null;
```
Comment (robbieaverill) [inline src/ORM/Connect/MySQLDatabase.php]: Protected over private?

File: .travis.yml [hunk 11]
```diff
@@ -20,20 +20,20 @@ matrix:
...
       env:
-        - DB=MYSQL
+        - DB=PGSQL
         - PHPCS_TEST=1
         - PHPUNIT_TEST=framework
 
     - php: 7.0
       env:
         - DB=PGSQL
+        - PDO=1
```
Comment (robbieaverill) [inline .travis.yml]: It'd probably be good to keep a PDO run on MySQL too

**Comment by sminnee** [comment]
> Somehow preserve the existing transaction behaviour - in a “legacy transaction manager” perhaps?

Yeah, we could potentially provide support for savepoint-based transactions on
 * Non-PDO connectors
 * PDO connectors with a "legacy" flag enabled, which would break all the type-correctness stuff

I could do this with a SavepointManager interface as a companion to TransactionManager, or something.

File: src/ORM/Connect/PDOConnector.php (hunk 5 above)
Comment (sminnee) [reply src/ORM/Connect/PDOConnector.php]: I don't necessarily disagree, although I should point out a previous discussion where you suggested that protected variables are part of our semver-governed "Public API". I'm worried about doing both.

I think that we should either treat protected properties that aren't explicitly documented as public API as "internal", or we use privates more often.

File: src/ORM/Connect/PDOConnector.php (hunk 3 above)
Comment (sminnee) [reply src/ORM/Connect/PDOConnector.php]: :+1:

File: .travis.yml (hunk 11 above)
Comment (sminnee) [reply .travis.yml]: one of the builds is7.2 / PDO / MySQL

File: src/ORM/Connect/PDOConnector.php (hunk 3 above)
Comment (sminnee) [reply src/ORM/Connect/PDOConnector.php]: Does removing this cause more strict linters to bark, though?

**Comment by sminnee** [comment]
@kinglozzer this c34c73f4ceea10a9e12d13745cebea1055c81b19 restores savepoint functionality, but if you want to use it on a PDO database, then you need to set this yaml config:

```
SilverStripe\ORM\Connect\PDOConnector:
  legacy_types: true
```

In effect it reverses the effect of this PR.

File: src/ORM/Connect/PDOConnector.php (hunk 5 above)
Comment (robbieaverill) [reply src/ORM/Connect/PDOConnector.php]: Yeah I guess it's a topic for another conversation, but at the moment our codebase is almost all protected over private so I guess we should keep it consistent?

File: .travis.yml (hunk 11 above)
Comment (robbieaverill) [reply .travis.yml]: Ah sweet, I looked but didn't see

File: src/ORM/Connect/PDOConnector.php (hunk 3 above)
Comment (robbieaverill) [reply src/ORM/Connect/PDOConnector.php]: It causes the slevomat standard to, yeah, but that'd be an issue to raise with them - this is fine in terms of the (proposed) PSR-5 spec =)

Comment (robbieaverill) [reply src/ORM/Connect/PDOConnector.php]: Actually, sounds like that standard prevents you from doing this anyway: https://github.com/slevomat/coding-standard/issues/399

File: src/ORM/Connect/MySQLDatabase.php (hunk 10 above)
Comment (sminnee) [reply src/ORM/Connect/MySQLDatabase.php]: No, it's got a getter that subclasses should use.

**Comment by kinglozzer** [comment]
Awesome, thanks @sminnee

File: src/ORM/Connect/PDOQuery.php [hunk 12]
```diff
@@ -22,16 +22,52 @@ class PDOQuery extends Query
      * Hook the result-set given into a Query class, suitable for use by SilverStripe.
      * @param PDOStatement $statement The internal PDOStatement containing the results
      */
-    public function __construct(PDOStatement $statement)
+    public function __construct(PDOStatement $statement, PDOConnector $conn)
```
Comment (kinglozzer) [inline src/ORM/Connect/PDOQuery.php]: Is `DB::get_conn()->getDriver()` an acceptable alternative to changing this method signature? I don’t feel too strongly about it given this is fairly internal

File: src/ORM/Connect/PDOQuery.php [hunk 13]
```diff
@@ -22,16 +22,52 @@ class PDOQuery extends Query
...
+        }
+
+        // Re-map fetched data using columnMeta
+        return array_map(
+            function ($rowArray) use ($columnMeta) {
+                $row = [];
+                foreach ($columnMeta as $i => $meta) {
+                    // Coerce floats from string to float
+                    // PDO PostgreSQL fails to do this
+                    if (isset($meta['native_type']) && preg_match('/^float/', $meta['native_type'])) {
```
Comment (kinglozzer) [inline src/ORM/Connect/PDOQuery.php]: Given this will be called on an unknown number of rows for each query, could/should we replace this with `strpos($meta['native_type'], 'float') === 0`?

File: src/ORM/Connect/PDOQuery.php [hunk 14]
```diff
@@ -22,16 +22,52 @@ class PDOQuery extends Query
...
+        } else {
+            $this->results = $statement->fetchAll(PDO::FETCH_ASSOC);
+        }
         $statement->closeCursor();
     }
 
+    /**
+     * Fetch a record form the statementw ith its type data corrected
+     * Necessary to fix float data retrieved from PGSQL
+     */
```
Comment (kinglozzer) [inline src/ORM/Connect/PDOQuery.php]: Missing param/return types

File: src/ORM/Connect/PDOQuery.php (hunk 13 above)
Comment (sminnee) [reply src/ORM/Connect/PDOQuery.php]: I'm pretty sure that preg_match is the fastest match. But we could also potentially get a list of all the options.

Comment (sminnee) [reply src/ORM/Connect/PDOQuery.php]: I stand corrected:
```
php test-preg.php 
preg... 3.5830228328705
strpos... 1.2603948116302
in_array... 1.4446079730988
```

```php
<?php

define('LOTS', 10000000);

profile('preg', function() {
  for ($i=0; $i<LOTS; $i++) {
    preg_match('/^float/', 'float8');
    preg_match('/^float/', 'float16');
    preg_match('/^float/', 'varchar');
    preg_match('/^float/', 'int');
  }
});

profile('strpos', function() {
  for ($i=0; $i<LOTS; $i++) {
    strpos('float8', 'float');
    strpos('float16', 'float');
    strpos('varchar', 'float');
    strpos('int', 'float');
  }
});

profile('in_array', function() {
    $array = ['float8', 'float16', 'float4'];
  for ($i=0; $i<LOTS; $i++) {
    in_array('float8', $array);
    in_array('float16', $array);
    in_array('varchar', $array);
    in_array('int', $array);
  }
});

function profile($label, $callback) {
    echo $label . "... ";
    $t1 = microtime(true);
    $callback();
    $t2 = microtime(true);
    echo ($t2-$t1) . "\n";
}
```

Comment (sminnee) [reply src/ORM/Connect/PDOQuery.php]: Still pretty close; i'm going with === 0 as it reduces the risk that i'm missing an entry in my array ;)

```
preg... 4.3494780063629
strpos... 1.7755749225616
in_array... 1.6038949489594
```

**Comment by sminnee** [comment]
OK @kinglozzer I've rebased and addressed a couple of points of your feedback, but left the changes to PDOQuery::__construct()'s method signature in place, as I thought that avoiding access to global state was more important than preserving this method signature. Notably, doing DB::get_conn() would block the creation of more than on dbConn object which is currently possible.

**Comment by sminnee** [comment]
It would be cool if we could merge https://github.com/silverstripe/silverstripe-postgresql/pull/91 so that I can retrigger these tests and get a green build before we merge.

**Comment by kinglozzer** [comment]
Thanks @sminnee! I’ve merged https://github.com/silverstripe/silverstripe-postgresql/pull/91 and will restart the build, if you can write up some brief docs then I think we’re good to merge

**Comment by sminnee** [comment]
Cool, so regarding docs, does this make sense?

 * DocBlock documentation for the TransactionManager interface
 * DocBlock documentation about the return types in the Query class
 * A "PHP Types" section in https://docs.silverstripe.org/en/4/developer_guides/model/sql_select/

Anything else?

**Comment by kinglozzer** [comment]
I think that just about covers it @sminnee, maybe a quick note in the changelog linking to the “PHP Types” section would be good too. Will leave this a few days anyway to give others the chance to review 👍

**Comment by sminnee** [comment]
OK @kinglozzer and @silverstripe/core-team - docs added, tests passing, ready to merge for 4.4.x-dev from my perspective!

**Comment by kinglozzer** [comment]
🎉 nice work @sminnee!
