### PR TITLE
BUG Capture errors after a reload token redirect to login url

### LINKED ISSUE #7289: BUG Some error conditions may forbid flushing on live mode
E.g. when requesting `url/flush=all`, the middleware may redirect to `Security/login` to authenticate on live mode.

However, occasionally an error may occur not on the first request, but on the second. In this case, perhaps ErrorControlChainMiddleware needs to be aware of nested parameters in the BackURL querystring arg.

I.e. if an error occurrs on `Security/login?BackURL=url%2F%3Fflush%3D1` then it should trigger the flush.

PR: https://github.com/silverstripe/silverstripe-framework/pull/7300

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #7289

### CODE REVIEW

File: src/Core/Startup/ParameterConfirmationToken.php [hunk 1]
```diff
@@ -136,6 +168,16 @@ public function parameterProvided()
     }
 
     /**
+     * Is the parmeter requested in a BackURL param?
+     *
+     * @return bool
+     */
+    public function parameterProvidedBackURL()
```
Comment (flamerohr) [inline src/Core/Startup/ParameterConfirmationToken.php]: This naming is a bit weird, `hasParameterBackURL()` or `hasBackURL()` would be more suited?

Or if you'd like stick to "Provided" perhaps `parameterBackURLProvided()`?

File: src/Core/Startup/ParameterConfirmationToken.php [hunk 2]
```diff
@@ -157,6 +199,18 @@ public function reloadRequired()
     }
 
     /**
+     * Check if this token is provided either in the backurl, or directly,
+     * but without a token
+     *
+     * @return bool
+     */
+    public function reloadOnError()
```
Comment (flamerohr) [inline src/Core/Startup/ParameterConfirmationToken.php]: the name reads like a command to action something rather than a checker, `shouldReloadOnError` perhaps?

File: src/Core/Startup/ParameterConfirmationToken.php (hunk 1 above)
Comment (tractorcow) [inline src/Core/Startup/ParameterConfirmationToken.php]: I've renamed to `existsInReferer`

File: src/Core/Startup/ParameterConfirmationToken.php (hunk 2 above)
Comment (tractorcow) [inline src/Core/Startup/ParameterConfirmationToken.php]: This method should match `reloadRequired`, so I've renamed to `reloadRequiredIfError` to be more explicit.

**Comment by tractorcow** [comment]
@flamerohr I've changed constants.php to prefer SS_BASE_URL instead of using the SCRIPT_FILENAME check, as it's not the least bit reliable on CLI.

What I've discovered is that running this on `phpdbg` gives the wrong BASE_URL at all.

**Comment by flamerohr** [comment]
Merging, travis is green but github hasn't updated
